## # Machine Learning - K Neighbour Classifier

### Step-01: Import all the libraries to perform Random Forest Classifier

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
import warnings
warnings.filterwarnings("ignore")

### Step-02: Import make_classification from sklearn.datasets

In [2]:
from sklearn.datasets import make_classification

In [3]:
x,y = make_classification(n_samples = 1000, n_features = 3, n_redundant = 1, n_classes = 2, random_state = 100) 

In [4]:
x

array([[ 0.16581305, -0.2757322 ,  1.38258121],
       [-0.02815775, -0.76081335,  1.44995386],
       [-0.46510864, -1.13319244,  0.09907462],
       ...,
       [-0.47821954, -1.17877844,  0.13032593],
       [-0.79635236, -1.11395581, -1.55399372],
       [-0.18765458, -0.87948511,  0.92085885]])

In [6]:
print("x: \n\n {} \n" .format(x))
print("x.shape: {} \n" .format(x.shape))

x: 

 [[ 0.16581305 -0.2757322   1.38258121]
 [-0.02815775 -0.76081335  1.44995386]
 [-0.46510864 -1.13319244  0.09907462]
 ...
 [-0.47821954 -1.17877844  0.13032593]
 [-0.79635236 -1.11395581 -1.55399372]
 [-0.18765458 -0.87948511  0.92085885]] 

x.shape: (1000, 3) 



In [7]:
y

array([0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1,
       1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1,
       0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1,
       0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1,
       0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1,
       0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1,
       0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1,

In [8]:
print("y: \n\n {} \n" .format(y))
print("y.shape: {} \n" .format(y.shape))

y: 

 [0 0 0 1 0 0 1 0 1 0 1 0 1 0 0 1 1 1 0 0 1 0 0 0 0 0 1 0 1 0 1 1 0 1 0 1 1
 0 0 0 0 0 1 0 0 1 1 0 1 1 1 1 1 0 1 1 0 1 1 0 1 1 0 1 0 1 1 1 1 0 0 1 0 0
 0 1 0 1 1 0 0 0 0 1 1 1 0 1 0 0 1 0 1 1 0 0 0 1 0 1 1 1 0 0 0 0 0 0 1 1 0
 1 0 0 1 1 0 1 0 1 1 1 1 0 0 1 0 0 1 0 0 0 0 1 0 0 1 1 1 1 1 1 1 1 1 0 0 0
 0 1 0 0 1 1 0 0 1 0 0 1 1 1 1 0 0 0 1 0 0 0 0 0 0 1 0 1 0 1 1 0 0 1 1 0 1
 1 0 0 1 0 0 0 1 0 0 0 0 1 1 0 1 1 1 1 1 1 1 0 1 1 0 0 0 1 0 1 1 0 1 1 0 1
 0 1 1 0 0 0 1 1 0 1 1 1 1 1 0 1 1 1 0 1 0 1 1 0 0 1 0 1 0 0 0 0 0 0 1 0 0
 1 1 0 0 0 1 0 1 0 1 1 1 0 0 1 0 0 0 0 1 0 0 0 0 0 0 0 1 1 1 1 0 0 0 0 1 0
 0 0 0 0 1 0 1 0 0 1 0 0 0 1 1 1 1 1 0 0 1 1 0 1 1 0 1 0 0 1 0 0 1 0 0 1 0
 1 0 1 0 1 0 1 1 1 1 0 1 1 1 0 0 1 1 0 1 0 0 0 1 1 1 1 1 0 1 0 1 0 0 1 1 0
 1 0 0 0 1 0 1 0 1 1 1 0 0 1 1 1 1 0 0 1 0 0 0 1 1 0 0 1 1 1 0 1 1 1 0 0 0
 0 1 1 0 0 1 1 0 0 0 0 1 0 1 0 1 1 0 1 1 0 0 0 0 1 1 0 1 1 1 1 1 1 0 0 0 0
 1 1 1 1 1 0 1 0 0 1 1 1 0 1 1 0 1 1 0 0 0 1 1 0 1 0 1 0 1 1 1 1 1 1 0 0 1
 0 1 0 1 1 0 0 0 0 

### Step-03: Import train_test_split from sklearn.model_selection

In [9]:
from sklearn.model_selection import train_test_split

In [10]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.3, random_state = 100)

In [11]:
x_train

array([[ 0.77478637,  1.13672266,  1.40148961],
       [ 0.54004173,  0.90656052,  0.73855686],
       [-1.08112758, -1.4169322 , -2.30865153],
       ...,
       [-0.71662565, -0.90640684, -1.59872584],
       [-0.77454467, -0.80963771, -2.08261492],
       [-0.53681829, -1.0413445 , -0.44170017]])

In [12]:
print("x_train: \n\n {} \n" .format(x_train))
print("x_train.shape: {} \n" .format(x_train.shape))

x_train: 

 [[ 0.77478637  1.13672266  1.40148961]
 [ 0.54004173  0.90656052  0.73855686]
 [-1.08112758 -1.4169322  -2.30865153]
 ...
 [-0.71662565 -0.90640684 -1.59872584]
 [-0.77454467 -0.80963771 -2.08261492]
 [-0.53681829 -1.0413445  -0.44170017]] 

x_train.shape: (700, 3) 



In [13]:
x_test

array([[ 4.94686227e-01,  7.29953531e-01,  8.86109013e-01],
       [-5.90120145e-01, -1.73158536e+00,  7.38603421e-01],
       [-5.95479406e-01, -1.64314922e+00,  5.28028724e-01],
       [-7.37267486e-01, -1.20430046e+00, -1.07782923e+00],
       [-5.46005511e-01, -1.64634442e+00,  7.75599504e-01],
       [-6.64027765e-01, -9.94349476e-01, -1.15915932e+00],
       [ 1.21038441e+00,  2.60712093e+00,  4.55303154e-01],
       [ 2.78585358e-01, -9.55023412e-01,  3.34871647e+00],
       [-5.49056881e-01, -9.76763979e-01, -6.36009704e-01],
       [-6.18555629e-01, -5.81710082e-01, -1.79850932e+00],
       [-6.16158110e-01, -9.91967074e-01, -9.31035073e-01],
       [-7.56939049e-01, -1.17223853e+00, -1.24049838e+00],
       [-5.36438603e-01, -1.59097083e+00,  7.06674275e-01],
       [-4.44225708e-01, -1.03650896e+00, -9.21765148e-04],
       [ 8.63618856e-01,  2.19918609e+00, -3.82262793e-01],
       [-7.25614922e-01, -1.05566405e+00, -1.33114579e+00],
       [-3.22708431e-01, -7.19351857e-01

In [14]:
print("x_test: \n\n {} \n" .format(x_test))
print("x_test.shape: {} \n" .format(x_test.shape))

x_test: 

 [[ 4.94686227e-01  7.29953531e-01  8.86109013e-01]
 [-5.90120145e-01 -1.73158536e+00  7.38603421e-01]
 [-5.95479406e-01 -1.64314922e+00  5.28028724e-01]
 [-7.37267486e-01 -1.20430046e+00 -1.07782923e+00]
 [-5.46005511e-01 -1.64634442e+00  7.75599504e-01]
 [-6.64027765e-01 -9.94349476e-01 -1.15915932e+00]
 [ 1.21038441e+00  2.60712093e+00  4.55303154e-01]
 [ 2.78585358e-01 -9.55023412e-01  3.34871647e+00]
 [-5.49056881e-01 -9.76763979e-01 -6.36009704e-01]
 [-6.18555629e-01 -5.81710082e-01 -1.79850932e+00]
 [-6.16158110e-01 -9.91967074e-01 -9.31035073e-01]
 [-7.56939049e-01 -1.17223853e+00 -1.24049838e+00]
 [-5.36438603e-01 -1.59097083e+00  7.06674275e-01]
 [-4.44225708e-01 -1.03650896e+00 -9.21765148e-04]
 [ 8.63618856e-01  2.19918609e+00 -3.82262793e-01]
 [-7.25614922e-01 -1.05566405e+00 -1.33114579e+00]
 [-3.22708431e-01 -7.19351857e-01 -7.08046504e-02]
 [-1.07235228e+00 -1.13955907e+00 -2.84452447e+00]
 [-9.31442277e-01 -1.15570383e+00 -2.12470666e+00]
 [ 7.20997143e-02 -8

In [15]:
y_train

array([1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1,
       1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1,
       0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0,
       1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1,
       1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1,
       0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0,
       0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1,
       1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0,
       0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1,
       0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1,

In [16]:
print("y_train: \n\n {} \n" .format(y_train))
print("y_train.shape: {} \n" .format(y_train.shape))

y_train: 

 [1 1 1 0 1 1 0 0 0 1 0 0 1 0 1 0 1 0 1 0 0 1 1 1 0 0 1 0 0 0 1 1 0 1 1 0 0
 1 1 1 0 1 0 1 0 1 1 1 1 1 0 1 0 0 0 0 0 0 1 0 1 0 1 0 0 0 1 0 1 1 0 0 0 0
 1 0 1 0 1 0 1 0 0 0 1 0 0 1 1 1 0 1 0 1 0 0 0 1 0 0 1 1 1 0 0 0 1 1 0 1 0
 0 1 1 0 1 1 1 1 0 1 0 1 1 0 0 1 1 0 0 0 1 0 0 0 0 0 0 1 0 0 1 0 1 1 0 1 0
 0 1 1 0 0 0 0 1 1 0 0 0 1 0 0 0 0 1 1 0 1 1 1 1 0 0 1 1 1 0 0 1 0 0 0 1 0
 0 0 0 0 1 0 1 0 1 0 1 1 1 0 0 0 1 0 0 0 1 1 1 0 0 0 1 1 1 0 0 0 1 1 0 0 0
 1 0 1 0 0 0 0 0 1 0 0 0 1 0 0 1 1 0 1 1 0 1 1 0 0 1 0 0 1 0 0 1 0 1 1 1 0
 0 1 0 1 1 1 0 0 1 1 0 0 0 1 1 1 0 0 1 1 1 0 1 0 1 0 1 0 1 0 1 1 0 1 1 0 0
 1 1 1 1 1 0 1 0 1 1 0 1 1 0 0 1 0 0 1 1 0 1 1 1 0 0 0 1 1 0 0 0 0 0 1 1 0
 0 1 1 1 1 1 0 0 1 0 1 0 1 0 0 0 1 0 0 0 1 0 1 0 1 1 1 1 0 1 1 1 0 1 0 0 0
 0 1 1 1 0 1 1 0 1 0 1 0 0 0 1 0 1 0 0 1 0 0 0 0 1 0 1 0 0 1 1 1 1 1 1 1 1
 0 1 0 0 1 0 1 0 1 1 0 1 1 0 0 1 0 0 1 1 1 1 0 0 1 0 0 1 0 0 0 1 1 1 1 0 0
 1 1 1 0 0 1 0 0 0 0 0 0 1 1 1 0 1 1 1 0 0 1 1 0 1 0 1 1 0 0 0 0 1 1 0 0 0
 1 0 1 0 0 0 

In [17]:
y_test

array([1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0,
       1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1,
       0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0,
       1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0,
       1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0,
       1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1,
       1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0,
       1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1,
       0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1])

In [18]:
print("y_test: \n\n {} \n" .format(y_test))
print("y_test.shape: {} \n" .format(y_test.shape))

y_test: 

 [1 0 0 0 0 0 1 1 0 1 0 0 0 0 1 0 0 0 0 1 1 1 0 0 0 1 1 1 0 0 1 1 1 1 1 1 1
 1 0 0 0 0 1 0 1 1 0 0 0 1 1 1 1 1 0 0 1 0 1 1 1 1 1 0 1 1 0 0 0 1 1 1 1 1
 0 0 0 1 1 1 1 1 0 1 0 0 0 1 0 0 0 1 0 1 1 0 0 1 0 0 1 1 1 1 1 1 1 0 1 1 1
 1 1 0 0 1 0 1 0 1 0 1 1 1 1 1 1 0 1 0 1 0 1 0 1 1 0 0 1 1 0 0 0 0 1 1 0 0
 1 0 0 0 1 1 0 0 0 0 1 1 1 1 0 1 0 1 0 1 1 0 1 1 1 1 1 0 1 1 1 0 0 0 0 1 0
 0 0 0 0 1 0 1 1 1 0 1 1 0 1 0 0 1 1 1 1 1 0 0 1 0 1 0 1 1 0 1 1 1 1 1 1 0
 1 0 0 0 0 1 1 1 1 1 0 0 1 1 1 1 0 0 0 1 0 1 0 1 1 1 1 0 1 1 1 0 1 1 1 0 1
 1 0 0 0 0 1 1 1 1 0 0 0 1 0 0 1 0 1 0 0 1 1 1 1 0 1 1 0 1 1 1 0 1 0 0 0 0
 0 1 1 1] 

y_test.shape: (300,) 



### Step-04: Import KNeighbourClassifier from sklearn.neighbours

In [19]:
from sklearn.neighbors import KNeighborsClassifier

In [20]:
k_neighbour = KNeighborsClassifier(n_neighbors = 5, algorithm = "auto")

In [21]:
k_neighbour.fit(x_train, y_train)

KNeighborsClassifier()

In [22]:
y_pred = k_neighbour.predict(x_test)

In [23]:
y_pred

array([1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0,
       1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1,
       0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0,
       1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0,
       1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0,
       1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1,
       0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1])

### Step-05: Import confusion_matrix, accuracy_score, classification_report from sklearn.metrics

In [25]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

In [26]:
print("Confusion Matrix: \n\n {} \n" .format(confusion_matrix(y_test, y_pred)))
print("Accuracy Score: {} \n" .format(accuracy_score(y_test, y_pred)))
print("Classification Report: \n\n {} \n" .format(classification_report(y_test, y_pred)))

Confusion Matrix: 

 [[125   8]
 [  6 161]] 

Accuracy Score: 0.9533333333333334 

Classification Report: 

               precision    recall  f1-score   support

           0       0.95      0.94      0.95       133
           1       0.95      0.96      0.96       167

    accuracy                           0.95       300
   macro avg       0.95      0.95      0.95       300
weighted avg       0.95      0.95      0.95       300
 



In [27]:
for k in range(1, 10):
    k_neighbour = KNeighborsClassifier(n_neighbors = k, algorithm = "auto")
    k_neighbour.fit(x_train, y_train)
    y_pred = k_neighbour.predict(x_test)
    print("for k = {}, accuracy = {}" .format(k, accuracy_score(y_test, y_pred)))

for k = 1, accuracy = 0.9333333333333333
for k = 2, accuracy = 0.9333333333333333
for k = 3, accuracy = 0.94
for k = 4, accuracy = 0.9433333333333334
for k = 5, accuracy = 0.9533333333333334
for k = 6, accuracy = 0.95
for k = 7, accuracy = 0.95
for k = 8, accuracy = 0.9533333333333334
for k = 9, accuracy = 0.9533333333333334


### Step-06: Import GridSearchCV from sklearn.model_selection

In [28]:
from sklearn.model_selection import GridSearchCV

In [32]:
parameters = {
    "n_neighbors": [1,2,3,4,5,6,7,8,9,10],
    "weights": ("uniform", "distance"),
    "algorithm": ("auto", "kd_tree", "ball_tree", "brute"),
    "p": [1,2]
}

In [33]:
grid_cv = GridSearchCV(k_neighbour, param_grid = parameters, scoring = "accuracy", cv = 5, verbose = 3)

In [34]:
grid_cv.fit(x_train, y_train)

Fitting 5 folds for each of 160 candidates, totalling 800 fits
[CV 1/5] END algorithm=auto, n_neighbors=1, p=1, weights=uniform;, score=0.914 total time=   0.0s
[CV 2/5] END algorithm=auto, n_neighbors=1, p=1, weights=uniform;, score=0.929 total time=   0.0s
[CV 3/5] END algorithm=auto, n_neighbors=1, p=1, weights=uniform;, score=0.936 total time=   0.0s
[CV 4/5] END algorithm=auto, n_neighbors=1, p=1, weights=uniform;, score=0.936 total time=   0.0s
[CV 5/5] END algorithm=auto, n_neighbors=1, p=1, weights=uniform;, score=0.957 total time=   0.0s
[CV 1/5] END algorithm=auto, n_neighbors=1, p=1, weights=distance;, score=0.914 total time=   0.0s
[CV 2/5] END algorithm=auto, n_neighbors=1, p=1, weights=distance;, score=0.929 total time=   0.0s
[CV 3/5] END algorithm=auto, n_neighbors=1, p=1, weights=distance;, score=0.936 total time=   0.0s
[CV 4/5] END algorithm=auto, n_neighbors=1, p=1, weights=distance;, score=0.936 total time=   0.0s
[CV 5/5] END algorithm=auto, n_neighbors=1, p=1, we

GridSearchCV(cv=5, estimator=KNeighborsClassifier(n_neighbors=9),
             param_grid={'algorithm': ('auto', 'kd_tree', 'ball_tree', 'brute'),
                         'n_neighbors': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
                         'p': [1, 2], 'weights': ('uniform', 'distance')},
             scoring='accuracy', verbose=3)

In [35]:
grid_cv.best_params_

{'algorithm': 'auto', 'n_neighbors': 4, 'p': 2, 'weights': 'uniform'}

In [36]:
grid_cv.best_score_

0.9457142857142857

In [37]:
y_pred = grid_cv.predict(x_test)

In [38]:
y_pred

array([1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0,
       1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1,
       0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0,
       1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0,
       1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0,
       1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0,
       1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1,
       0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1])

In [39]:
print("Confusion Matrix: \n\n {} \n" .format(confusion_matrix(y_test, y_pred)))
print("Accuracy Score: {} \n" .format(accuracy_score(y_test, y_pred)))
print("Classification Report: \n\n {} \n" .format(classification_report(y_test, y_pred)))

Confusion Matrix: 

 [[127   6]
 [ 11 156]] 

Accuracy Score: 0.9433333333333334 

Classification Report: 

               precision    recall  f1-score   support

           0       0.92      0.95      0.94       133
           1       0.96      0.93      0.95       167

    accuracy                           0.94       300
   macro avg       0.94      0.94      0.94       300
weighted avg       0.94      0.94      0.94       300
 

