## # Machine Learning - K Neighbour Regressor

### Step-01: Import all the libraries to perform Random Forest Regressor

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
import warnings
warnings.filterwarnings("ignore")

### Step-02: Import make_regression from sklearn.datasets

In [2]:
from sklearn.datasets import make_regression

In [3]:
x,y = make_regression(n_samples = 1000, n_features = 3, n_informative = 2, n_targets = 1, noise = 10.0, random_state = 100)

In [4]:
x

array([[-1.26260429,  0.53846601, -1.02319884],
       [ 0.86865026,  0.53336626,  0.11248681],
       [-0.6017025 , -1.02807068,  0.26686482],
       ...,
       [-0.38408693, -1.24677147,  0.40445167],
       [-0.52451706, -1.89152317,  0.38976153],
       [ 0.64435936,  0.81169105, -0.14505356]])

In [5]:
print("x: \n\n {} \n" .format(x))
print("x.shape: {} \n" .format(x.shape))

x: 

 [[-1.26260429  0.53846601 -1.02319884]
 [ 0.86865026  0.53336626  0.11248681]
 [-0.6017025  -1.02807068  0.26686482]
 ...
 [-0.38408693 -1.24677147  0.40445167]
 [-0.52451706 -1.89152317  0.38976153]
 [ 0.64435936  0.81169105 -0.14505356]] 

x.shape: (1000, 3) 



In [6]:
y

array([-1.31451645e+02,  7.05032884e+01, -4.14686075e+01,  5.47183237e+00,
       -6.20870224e+01, -3.04553951e+01, -1.54844241e+02, -2.68940751e+01,
       -5.52335505e+01,  7.67245539e+01, -1.07294729e+02, -5.57427783e+01,
        1.54693304e+02,  9.58159091e+01,  1.27397382e+01, -3.29753767e+01,
        1.30333976e+02,  2.08293610e+01,  6.02757542e+01,  6.00176311e+00,
        5.91390154e+01,  1.93481857e+01, -1.26623917e+02, -3.41718300e+01,
       -2.13795527e+02, -5.87729919e+01,  2.42878501e+00,  3.17477614e+01,
       -1.90062357e+01,  1.21847743e+02,  7.39927446e+01,  1.28681283e+02,
       -8.01081459e+00,  3.27305420e+01, -4.73213746e+00, -1.60070976e+01,
        2.08282360e+01,  1.91354519e+02,  2.93434157e+00, -9.64694970e+01,
       -1.02821742e+00, -1.06273753e+02,  1.02736746e+02,  1.20502119e+02,
        2.04280836e+01,  7.30382606e+01,  8.86106383e+01,  4.87482141e+00,
       -3.58918488e+01,  8.64627399e+01,  9.48792332e+01, -5.68065110e+01,
       -9.69431527e+01,  

In [7]:
print("y: \n\n {} \n" .format(y))
print("y.shape: {} \n" .format(y.shape))

y: 

 [-1.31451645e+02  7.05032884e+01 -4.14686075e+01  5.47183237e+00
 -6.20870224e+01 -3.04553951e+01 -1.54844241e+02 -2.68940751e+01
 -5.52335505e+01  7.67245539e+01 -1.07294729e+02 -5.57427783e+01
  1.54693304e+02  9.58159091e+01  1.27397382e+01 -3.29753767e+01
  1.30333976e+02  2.08293610e+01  6.02757542e+01  6.00176311e+00
  5.91390154e+01  1.93481857e+01 -1.26623917e+02 -3.41718300e+01
 -2.13795527e+02 -5.87729919e+01  2.42878501e+00  3.17477614e+01
 -1.90062357e+01  1.21847743e+02  7.39927446e+01  1.28681283e+02
 -8.01081459e+00  3.27305420e+01 -4.73213746e+00 -1.60070976e+01
  2.08282360e+01  1.91354519e+02  2.93434157e+00 -9.64694970e+01
 -1.02821742e+00 -1.06273753e+02  1.02736746e+02  1.20502119e+02
  2.04280836e+01  7.30382606e+01  8.86106383e+01  4.87482141e+00
 -3.58918488e+01  8.64627399e+01  9.48792332e+01 -5.68065110e+01
 -9.69431527e+01  6.98550363e+01 -1.16404180e+02  9.83812791e+01
  1.42330390e+01  5.61670732e+01 -1.11619972e+02 -4.39282890e+01
  5.44786326e+01  1

### Step-03: Import train_test_split from sklearn.model_selection

In [8]:
from sklearn.model_selection import train_test_split

In [9]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.3, random_state = 100)

In [10]:
x_train

array([[-1.52271454e-03, -5.20612810e-01,  4.03498620e-01],
       [-3.36656219e-01, -5.35004800e-01, -1.09411240e+00],
       [-1.48934344e+00,  5.49930597e-01, -4.88451870e-02],
       ...,
       [-1.64556309e+00,  2.73919709e-01, -1.08327246e+00],
       [ 1.12088662e+00, -1.36549988e+00, -8.12278669e-01],
       [ 2.22047449e-01,  5.04730196e-01,  9.02303533e-01]])

In [11]:
print("x_train: \n\n {} \n" .format(x_train))
print("x_train.shape: {} \n" .format(x_train.shape))

x_train: 

 [[-1.52271454e-03 -5.20612810e-01  4.03498620e-01]
 [-3.36656219e-01 -5.35004800e-01 -1.09411240e+00]
 [-1.48934344e+00  5.49930597e-01 -4.88451870e-02]
 ...
 [-1.64556309e+00  2.73919709e-01 -1.08327246e+00]
 [ 1.12088662e+00 -1.36549988e+00 -8.12278669e-01]
 [ 2.22047449e-01  5.04730196e-01  9.02303533e-01]] 

x_train.shape: (700, 3) 



In [12]:
x_test

array([[ 3.07557389e+00, -8.78268168e-01,  8.30819564e-01],
       [-1.60248453e+00, -6.97530591e-01, -6.04830150e-02],
       [ 5.74540044e-02, -7.50132368e-01, -4.18725184e-01],
       [-3.59283629e-02, -8.15457869e-01, -6.53472322e-01],
       [ 1.27179427e+00,  2.08061671e+00,  1.03238309e+00],
       [ 2.07541179e-02, -1.18336380e+00, -6.00619281e-01],
       [-2.67225301e-01, -2.67591922e-01,  1.32423802e+00],
       [ 2.44207071e-01,  1.61693990e+00,  1.03234591e+00],
       [-5.00474411e-01,  1.53455299e+00,  6.87625951e-01],
       [-1.83387374e+00, -1.58591320e-01, -2.89224041e+00],
       [ 9.72114439e-02,  6.11474932e-01,  2.74524295e-01],
       [-2.27190550e+00,  8.76051185e-01,  7.57604988e-01],
       [-1.59044859e+00, -1.22143589e-01, -3.33843175e-01],
       [ 5.39172445e-01, -7.68403397e-02,  1.19882394e+00],
       [ 7.93060552e-01, -5.70586918e-02, -4.23823577e-02],
       [-8.10560116e-01, -7.90472711e-01,  1.99985784e+00],
       [-4.41114481e-01, -1.00137811e-01

In [13]:
print("x_test: \n\n {} \n" .format(x_test))
print("x_test.shape: {} \n" .format(x_test.shape))

x_test: 

 [[ 3.07557389e+00 -8.78268168e-01  8.30819564e-01]
 [-1.60248453e+00 -6.97530591e-01 -6.04830150e-02]
 [ 5.74540044e-02 -7.50132368e-01 -4.18725184e-01]
 [-3.59283629e-02 -8.15457869e-01 -6.53472322e-01]
 [ 1.27179427e+00  2.08061671e+00  1.03238309e+00]
 [ 2.07541179e-02 -1.18336380e+00 -6.00619281e-01]
 [-2.67225301e-01 -2.67591922e-01  1.32423802e+00]
 [ 2.44207071e-01  1.61693990e+00  1.03234591e+00]
 [-5.00474411e-01  1.53455299e+00  6.87625951e-01]
 [-1.83387374e+00 -1.58591320e-01 -2.89224041e+00]
 [ 9.72114439e-02  6.11474932e-01  2.74524295e-01]
 [-2.27190550e+00  8.76051185e-01  7.57604988e-01]
 [-1.59044859e+00 -1.22143589e-01 -3.33843175e-01]
 [ 5.39172445e-01 -7.68403397e-02  1.19882394e+00]
 [ 7.93060552e-01 -5.70586918e-02 -4.23823577e-02]
 [-8.10560116e-01 -7.90472711e-01  1.99985784e+00]
 [-4.41114481e-01 -1.00137811e-01  1.19483295e-02]
 [-2.64583680e-01  2.23824119e-01  3.53005183e-01]
 [-1.27031804e+00 -2.98435671e-01  6.35501168e-01]
 [-1.01648111e+00 -9

In [14]:
y_train

array([   9.52116858,  -80.64618342,  -75.68107861,   77.84736714,
         51.73888904,   41.98163252,  -84.52786629,  -53.72529595,
       -141.66312861,  -46.14228696,   -6.80965406,   25.49625448,
          2.07348232,    4.18594326,  -12.61408588,   96.11657714,
        -25.01350327,   48.85807994,   34.64342957,  -43.92828903,
         29.5466646 ,  102.73674634,  -61.88961009,   93.32888196,
         89.3563644 ,  104.22045728, -169.37123864,  -29.82629464,
        -49.67306266,   52.89031373,    5.47183237,   42.37333255,
          3.00661679,  100.24558698,   96.07027141,  -23.22159335,
        111.83142793,   42.64523623,  -53.863761  ,  128.68128336,
        -48.56201556,  -13.97873235,   68.12188413,  -25.30439988,
         17.72327634,   44.30987312,  -68.90170545,  -33.15755082,
        183.78919138,  -38.83979039,   -9.16172873,  -98.39329708,
         94.36857479,    3.94303524,   12.78646381,   -9.63512393,
         76.70519419,  160.85368587,  -64.37967697,   63.78171

In [15]:
print("y_train: \n\n {} \n" .format(y_train))
print("y_train.shape: {} \n" .format(y_train.shape))

y_train: 

 [   9.52116858  -80.64618342  -75.68107861   77.84736714   51.73888904
   41.98163252  -84.52786629  -53.72529595 -141.66312861  -46.14228696
   -6.80965406   25.49625448    2.07348232    4.18594326  -12.61408588
   96.11657714  -25.01350327   48.85807994   34.64342957  -43.92828903
   29.5466646   102.73674634  -61.88961009   93.32888196   89.3563644
  104.22045728 -169.37123864  -29.82629464  -49.67306266   52.89031373
    5.47183237   42.37333255    3.00661679  100.24558698   96.07027141
  -23.22159335  111.83142793   42.64523623  -53.863761    128.68128336
  -48.56201556  -13.97873235   68.12188413  -25.30439988   17.72327634
   44.30987312  -68.90170545  -33.15755082  183.78919138  -38.83979039
   -9.16172873  -98.39329708   94.36857479    3.94303524   12.78646381
   -9.63512393   76.70519419  160.85368587  -64.37967697   63.7817162
 -126.42156843    0.30235417  -87.51350912  124.33204851   29.94528508
   59.13001725  -10.00156663  -63.63423943    3.80988785  -40.42199

In [16]:
y_test

array([ 2.35022718e+02, -1.12464439e+02,  3.62487705e+00, -4.01954658e+01,
        1.16832980e+02, -2.22278006e+01,  5.74362931e+01,  7.57465849e+01,
        9.76871376e+00, -2.50294428e+02,  2.04523144e+01, -8.93965782e+01,
       -1.15036711e+02,  8.36175443e+01,  5.91914313e+01,  5.12447667e+01,
       -2.79748440e+01, -1.15422957e+00, -4.85679832e+01,  1.36033377e+01,
        6.72830808e+01,  1.00529194e+02,  1.87876651e+01,  2.04280836e+01,
       -4.25988115e+01, -2.41963129e+01,  1.30565498e+02, -3.58918488e+01,
        3.91276465e+00,  4.42558599e+00, -4.56165206e+01, -1.19911933e+02,
       -1.76512266e+02,  1.25025762e+02,  2.58992001e+01, -7.70242778e+01,
        1.21579308e+02,  1.80146413e+01, -9.45088776e+01, -5.22484191e+01,
        2.00580371e+02,  2.32183029e+01, -4.04784112e+01, -1.87627509e+02,
       -8.23633159e+01, -1.33004891e+02,  1.64151325e+01, -7.74324722e+01,
       -1.62182993e+01, -8.27797648e+01, -4.20002255e+01, -4.35536193e+00,
       -1.60935867e+01, -

In [17]:
print("y_test: \n\n {} \n" .format(y_test))
print("y_test.shape: {} \n" .format(y_test.shape))

y_test: 

 [ 2.35022718e+02 -1.12464439e+02  3.62487705e+00 -4.01954658e+01
  1.16832980e+02 -2.22278006e+01  5.74362931e+01  7.57465849e+01
  9.76871376e+00 -2.50294428e+02  2.04523144e+01 -8.93965782e+01
 -1.15036711e+02  8.36175443e+01  5.91914313e+01  5.12447667e+01
 -2.79748440e+01 -1.15422957e+00 -4.85679832e+01  1.36033377e+01
  6.72830808e+01  1.00529194e+02  1.87876651e+01  2.04280836e+01
 -4.25988115e+01 -2.41963129e+01  1.30565498e+02 -3.58918488e+01
  3.91276465e+00  4.42558599e+00 -4.56165206e+01 -1.19911933e+02
 -1.76512266e+02  1.25025762e+02  2.58992001e+01 -7.70242778e+01
  1.21579308e+02  1.80146413e+01 -9.45088776e+01 -5.22484191e+01
  2.00580371e+02  2.32183029e+01 -4.04784112e+01 -1.87627509e+02
 -8.23633159e+01 -1.33004891e+02  1.64151325e+01 -7.74324722e+01
 -1.62182993e+01 -8.27797648e+01 -4.20002255e+01 -4.35536193e+00
 -1.60935867e+01 -1.01591124e+02 -2.66658506e+01  1.20502119e+02
  1.66307178e+01  6.46255759e+01 -9.11714390e+01 -6.40309119e+01
  1.16903960e+

### Step-04: Import KNeighbourRegressor from sklearn.neighbours

In [18]:
from sklearn.neighbors import KNeighborsRegressor

In [19]:
k_neighbour = KNeighborsRegressor(n_neighbors = 5, algorithm = "auto")

In [20]:
k_neighbour.fit(x_train, y_train)

KNeighborsRegressor()

In [21]:
y_pred = k_neighbour.predict(x_test)

In [22]:
y_pred

array([ 194.51760139,  -94.27746481,  -14.04989057,  -43.97819653,
        107.40443405,  -11.20190381,   48.36653149,   60.9734296 ,
          8.82836897, -188.47964072,   16.65486107, -110.06974627,
       -110.3777044 ,  102.03551239,   34.22440738,   41.36675047,
        -25.26656661,   -7.58482419,  -37.73860885,   -2.09894401,
         50.12914667,   86.65443172,   25.20955331,   29.74339723,
        -50.18977029,  -33.61011592,  122.64838202,   -4.02169155,
        -20.96442266,    0.90882872,  -51.15101502, -109.91392965,
       -155.28264653,  115.66144958,   37.04978826,  -61.48567789,
         85.27140678,   23.69916228,  -73.99712042,  -44.89232113,
        160.5701044 ,   43.14171164,  -48.2570287 , -116.63652267,
        -83.19952822, -143.69360371,   16.31024892,  -61.9531073 ,
         -4.71399942,  -82.84110774,  -45.62798605,   12.97248728,
        -38.5514899 ,  -82.88571829,  -32.81604694,  108.00779049,
          4.42255067,   49.31732322,  -75.08438057,  -75.29388

### Step-05: Import r2_score from sklearn.metrics

In [23]:
from sklearn.metrics import r2_score

In [24]:
print("Accuracy: {}" .format(r2_score(y_test, y_pred)))

Accuracy: 0.951530384465565


In [25]:
for k in range(1, 10):
    k_neighbour = KNeighborsRegressor(n_neighbors = k, algorithm = "auto")
    k_neighbour.fit(x_train, y_train)
    y_pred = k_neighbour.predict(x_test)
    print("for k = {}, accuracy = {}" .format(k, r2_score(y_test, y_pred)))

for k = 1, accuracy = 0.9334865453844384
for k = 2, accuracy = 0.951694578212217
for k = 3, accuracy = 0.954628279213555
for k = 4, accuracy = 0.9536309969367754
for k = 5, accuracy = 0.951530384465565
for k = 6, accuracy = 0.9525413332184594
for k = 7, accuracy = 0.9494325438435951
for k = 8, accuracy = 0.9488592512234874
for k = 9, accuracy = 0.9471449525318083


### Step-06: Import GridSearchCV from sklearn.model_selection

In [26]:
from sklearn.model_selection import GridSearchCV

In [27]:
parameters = {
    "n_neighbors": [1,2,3,4,5,6,7,8,9,10],
    "weights": ("uniform", "distance"),
    "algorithm": ("auto", "kd_tree", "ball_tree", "brute"),
    "p": [1,2]
}

In [29]:
grid_cv = GridSearchCV(k_neighbour, param_grid = parameters, scoring = "r2", cv = 5, verbose = 3)

In [30]:
grid_cv.fit(x_train, y_train)

Fitting 5 folds for each of 160 candidates, totalling 800 fits
[CV 1/5] END algorithm=auto, n_neighbors=1, p=1, weights=uniform;, score=0.914 total time=   0.0s
[CV 2/5] END algorithm=auto, n_neighbors=1, p=1, weights=uniform;, score=0.921 total time=   0.0s
[CV 3/5] END algorithm=auto, n_neighbors=1, p=1, weights=uniform;, score=0.930 total time=   0.0s
[CV 4/5] END algorithm=auto, n_neighbors=1, p=1, weights=uniform;, score=0.910 total time=   0.0s
[CV 5/5] END algorithm=auto, n_neighbors=1, p=1, weights=uniform;, score=0.926 total time=   0.0s
[CV 1/5] END algorithm=auto, n_neighbors=1, p=1, weights=distance;, score=0.914 total time=   0.0s
[CV 2/5] END algorithm=auto, n_neighbors=1, p=1, weights=distance;, score=0.921 total time=   0.0s
[CV 3/5] END algorithm=auto, n_neighbors=1, p=1, weights=distance;, score=0.930 total time=   0.0s
[CV 4/5] END algorithm=auto, n_neighbors=1, p=1, weights=distance;, score=0.910 total time=   0.0s
[CV 5/5] END algorithm=auto, n_neighbors=1, p=1, we

GridSearchCV(cv=5, estimator=KNeighborsRegressor(n_neighbors=9),
             param_grid={'algorithm': ('auto', 'kd_tree', 'ball_tree', 'brute'),
                         'n_neighbors': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
                         'p': [1, 2], 'weights': ('uniform', 'distance')},
             scoring='r2', verbose=3)

In [31]:
grid_cv.best_params_

{'algorithm': 'auto', 'n_neighbors': 5, 'p': 2, 'weights': 'distance'}

In [32]:
grid_cv.best_score_

0.9530268151753768

In [33]:
y_pred = grid_cv.predict(x_test)

In [34]:
y_pred

array([ 1.96615109e+02, -9.39732626e+01, -1.34951119e+01, -4.33300770e+01,
        1.07004894e+02, -1.72557832e+01,  4.82622230e+01,  6.67694951e+01,
        8.91612354e+00, -1.95359017e+02,  1.54442086e+01, -1.10608074e+02,
       -1.10982380e+02,  9.94071649e+01,  3.81297646e+01,  4.01400592e+01,
       -2.59142029e+01, -8.27352129e+00, -3.88548677e+01, -4.47369307e+00,
        5.53103637e+01,  9.21727317e+01,  2.49868696e+01,  3.03286200e+01,
       -4.90865793e+01, -3.39333664e+01,  1.27753948e+02, -1.41939396e+00,
       -2.28055873e+01,  1.27712171e-01, -4.79423532e+01, -1.10846217e+02,
       -1.52720927e+02,  1.16982966e+02,  3.27003709e+01, -6.47102417e+01,
        8.34544308e+01,  2.48759273e+01, -7.24833702e+01, -4.35551571e+01,
        1.60789059e+02,  4.43925590e+01, -4.32008084e+01, -1.21842550e+02,
       -8.45225986e+01, -1.43641808e+02,  1.47286075e+01, -6.10629257e+01,
       -6.97589221e+00, -8.36259105e+01, -4.67980369e+01,  1.54007986e+01,
       -3.66178278e+01, -

In [35]:
print("Accuracy: {}" .format(r2_score(y_test, y_pred)))

Accuracy: 0.9559723379025968
