## # Logistic Regression - Multiclass Classification

###  Step-01: Import all the libraries that are required to perform logistic regression

In [1]:
import pandas as np
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
import warnings
warnings.filterwarnings("ignore")

### Step-02: Import make_classification from sklearn.datasets

In [2]:
from sklearn.datasets import make_classification

In [3]:
x,y = make_classification(n_samples = 1000, n_features = 10, n_informative = 5, n_redundant = 5, n_classes = 3, random_state = 42)

### Step-03: Import train_test_split from sklearn.model_selection

In [4]:
from sklearn.model_selection import train_test_split

In [5]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 42)

### Step-04: Import LogisticRegression from sklearn.linear_model

In [6]:
from sklearn.linear_model import LogisticRegression

In [7]:
classifier = LogisticRegression(multi_class = "ovr", solver = "lbfgs")

In [8]:
classifier

LogisticRegression(multi_class='ovr')

In [9]:
classifier.fit(x_train, y_train)

LogisticRegression(multi_class='ovr')

In [10]:
y_pred = classifier.predict(x_test)

In [11]:
y_pred

array([1, 0, 1, 1, 0, 0, 1, 2, 2, 2, 0, 0, 0, 0, 0, 0, 2, 1, 2, 1, 2, 2,
       0, 0, 0, 0, 1, 2, 0, 0, 1, 0, 2, 2, 1, 1, 0, 1, 1, 0, 0, 2, 2, 2,
       2, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 2, 1, 0, 1, 1, 0, 0, 2, 1, 0,
       0, 0, 1, 2, 2, 0, 1, 2, 2, 1, 2, 0, 0, 0, 0, 2, 2, 1, 2, 2, 0, 2,
       0, 1, 1, 1, 1, 1, 0, 1, 0, 2, 2, 2, 1, 0, 1, 1, 2, 1, 1, 2, 0, 1,
       2, 0, 0, 2, 2, 2, 0, 1, 2, 1, 2, 0, 1, 0, 0, 0, 1, 2, 0, 2, 0, 0,
       2, 1, 0, 2, 0, 1, 2, 1, 0, 2, 1, 0, 2, 0, 2, 2, 1, 1, 0, 0, 0, 2,
       1, 0, 1, 0, 0, 2, 2, 1, 1, 0, 0, 1, 0, 0, 0, 2, 2, 0, 2, 2, 1, 2,
       1, 1, 2, 0, 1, 1, 0, 0, 2, 2, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 1])

In [12]:
y_pred_proba = classifier.predict_proba(x_test)

### Step-05: Import confusion_matrix, accuracy_score, classification_report from sklearn.metrics

In [14]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

In [15]:
print("Confusion Matrix: \n {}".format(confusion_matrix(y_test, y_pred)))
print("Accuracy Score: \n {}".format(accuracy_score(y_test, y_pred)))
print("Classification Report: \n {}".format(classification_report(y_test, y_pred)))

Confusion Matrix: 
 [[54  7  7]
 [ 6 45 14]
 [14 17 36]]
Accuracy Score: 
 0.675
Classification Report: 
               precision    recall  f1-score   support

           0       0.73      0.79      0.76        68
           1       0.65      0.69      0.67        65
           2       0.63      0.54      0.58        67

    accuracy                           0.68       200
   macro avg       0.67      0.67      0.67       200
weighted avg       0.67      0.68      0.67       200

