In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [19]:
np.c_[[1,1], -np.ones((len([1,1]), 1))]

array([[ 1., -1.],
       [ 1., -1.]])

In [31]:
class Perceptron:
    
    def __init__ (self, eta, epochs):
        
        self.weights = np.random.randn(2) * 1e-4
        print("self weights: {}" .format(self.weights))
        self.eta = eta
        self.epochs = epochs
    
    def activation_function (self, inputs, weights):
        
        z = np.dot(inputs, weights)
        return np.where(z > 1, 1, 0)
    
    def fit (self, x, y):
        
        self.x = x
        self.y = y
        
        # x_with_bias = np.c_[self.x, -np.ones((len(self.x), 1))]
        # print("x_with_bias: \n{}" .format(x_with_bias))
        
        for epoch in range(self.epochs):
            print("for epoch: {}" .format(epoch))
            y_hat = self.activation_function(self.x, self.weights)
            print("predicted value: \n{}" .format(y_hat))
            error = y_hat - self.y
            print("error: \n{}" .format(error))
            self.weights = self.weights - self.eta * np.dot(self.x.T, error)
            print("updated weights: \n{}" .format(self.weights))
            
    def predict (self, x):
        
        return self.activation_function(x, self.weights)

In [21]:
data = {"x1": [0,0,1,1], "x2": [0,1,0,1], "y": [0,0,0,1]}

AND = pd.DataFrame(data)
AND

x1  x2  y
0   0   0  0
1   0   1  0
2   1   0  0
3   1   1  1

In [22]:
X = AND.drop("y", axis = 1)
X

x1  x2
0   0   0
1   0   1
2   1   0
3   1   1

In [25]:
y = AND["y"]
y.to_frame()

y
0  0
1  0
2  0
3  1

In [32]:
model = Perceptron(eta = 0.5, epochs = 10)
model.fit(X,y)

self weights: [-4.71562639e-05  1.86373235e-05]
for epoch: 0
predicted value: 
[0 0 0 0]
error: 
0    0
1    0
2    0
3   -1
Name: y, dtype: int64
updated weights: 
[0.49995284 0.50001864]
for epoch: 1
predicted value: 
[0 0 0 0]
error: 
0    0
1    0
2    0
3   -1
Name: y, dtype: int64
updated weights: 
[0.99995284 1.00001864]
for epoch: 2
predicted value: 
[0 1 0 1]
error: 
0    0
1    1
2    0
3    0
Name: y, dtype: int64
updated weights: 
[0.99995284 0.50001864]
for epoch: 3
predicted value: 
[0 0 0 1]
error: 
0    0
1    0
2    0
3    0
Name: y, dtype: int64
updated weights: 
[0.99995284 0.50001864]
for epoch: 4
predicted value: 
[0 0 0 1]
error: 
0    0
1    0
2    0
3    0
Name: y, dtype: int64
updated weights: 
[0.99995284 0.50001864]
for epoch: 5
predicted value: 
[0 0 0 1]
error: 
0    0
1    0
2    0
3    0
Name: y, dtype: int64
updated weights: 
[0.99995284 0.50001864]
for epoch: 6
predicted value: 
[0 0 0 1]
error: 
0    0
1    0
2    0
3    0
Name: y, dtype: int64
updated