## # Machine Learning - Random Forest Regressor

### Step-01: Import all the libraries to perform Random Forest Regressor

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
import warnings
warnings.filterwarnings("ignore")

In [2]:
df = sns.load_dataset("tips")

In [3]:
df.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [4]:
print("df.head(): \n\n {} \n" .format(df.head()))
print("df.shape: {} \n" .format(df.shape))

df.head(): 

    total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4 

df.shape: (244, 7) 



In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype   
---  ------      --------------  -----   
 0   total_bill  244 non-null    float64 
 1   tip         244 non-null    float64 
 2   sex         244 non-null    category
 3   smoker      244 non-null    category
 4   day         244 non-null    category
 5   time        244 non-null    category
 6   size        244 non-null    int64   
dtypes: category(4), float64(2), int64(1)
memory usage: 7.4 KB


In [6]:
df.describe()

total_bill         tip        size
count  244.000000  244.000000  244.000000
mean    19.785943    2.998279    2.569672
std      8.902412    1.383638    0.951100
min      3.070000    1.000000    1.000000
25%     13.347500    2.000000    2.000000
50%     17.795000    2.900000    2.000000
75%     24.127500    3.562500    3.000000
max     50.810000   10.000000    6.000000

In [7]:
df.isnull().sum()

total_bill    0
tip           0
sex           0
smoker        0
day           0
time          0
size          0
dtype: int64

In [8]:
df["day"].unique()

['Sun', 'Sat', 'Thur', 'Fri']
Categories (4, object): ['Thur', 'Fri', 'Sat', 'Sun']

In [9]:
df["time"].unique()

['Dinner', 'Lunch']
Categories (2, object): ['Lunch', 'Dinner']

In [10]:
df["day"].value_counts()

Sat     87
Sun     76
Thur    62
Fri     19
Name: day, dtype: int64

In [11]:
df["time"].value_counts()

Dinner    176
Lunch      68
Name: time, dtype: int64

In [12]:
x = df.drop("total_bill", axis = 1)
y = np.array(list(df["total_bill"]))

In [13]:
x.head()

tip     sex smoker  day    time  size
0  1.01  Female     No  Sun  Dinner     2
1  1.66    Male     No  Sun  Dinner     3
2  3.50    Male     No  Sun  Dinner     3
3  3.31    Male     No  Sun  Dinner     2
4  3.61  Female     No  Sun  Dinner     4

In [14]:
print("x.head(): \n\n {} \n" .format(x.head()))
print("x.shape: {} \n" .format(x.shape))

x.head(): 

     tip     sex smoker  day    time  size
0  1.01  Female     No  Sun  Dinner     2
1  1.66    Male     No  Sun  Dinner     3
2  3.50    Male     No  Sun  Dinner     3
3  3.31    Male     No  Sun  Dinner     2
4  3.61  Female     No  Sun  Dinner     4 

x.shape: (244, 6) 



In [15]:
y

array([16.99, 10.34, 21.01, 23.68, 24.59, 25.29,  8.77, 26.88, 15.04,
       14.78, 10.27, 35.26, 15.42, 18.43, 14.83, 21.58, 10.33, 16.29,
       16.97, 20.65, 17.92, 20.29, 15.77, 39.42, 19.82, 17.81, 13.37,
       12.69, 21.7 , 19.65,  9.55, 18.35, 15.06, 20.69, 17.78, 24.06,
       16.31, 16.93, 18.69, 31.27, 16.04, 17.46, 13.94,  9.68, 30.4 ,
       18.29, 22.23, 32.4 , 28.55, 18.04, 12.54, 10.29, 34.81,  9.94,
       25.56, 19.49, 38.01, 26.41, 11.24, 48.27, 20.29, 13.81, 11.02,
       18.29, 17.59, 20.08, 16.45,  3.07, 20.23, 15.01, 12.02, 17.07,
       26.86, 25.28, 14.73, 10.51, 17.92, 27.2 , 22.76, 17.29, 19.44,
       16.66, 10.07, 32.68, 15.98, 34.83, 13.03, 18.28, 24.71, 21.16,
       28.97, 22.49,  5.75, 16.32, 22.75, 40.17, 27.28, 12.03, 21.01,
       12.46, 11.35, 15.38, 44.3 , 22.42, 20.92, 15.36, 20.49, 25.21,
       18.24, 14.31, 14.  ,  7.25, 38.07, 23.95, 25.71, 17.31, 29.93,
       10.65, 12.43, 24.08, 11.69, 13.42, 14.26, 15.95, 12.48, 29.8 ,
        8.52, 14.52,

In [16]:
print("y: \n\n {} \n" .format(y))
print("y.shape: {} \n" .format(y.shape))

y: 

 [16.99 10.34 21.01 23.68 24.59 25.29  8.77 26.88 15.04 14.78 10.27 35.26
 15.42 18.43 14.83 21.58 10.33 16.29 16.97 20.65 17.92 20.29 15.77 39.42
 19.82 17.81 13.37 12.69 21.7  19.65  9.55 18.35 15.06 20.69 17.78 24.06
 16.31 16.93 18.69 31.27 16.04 17.46 13.94  9.68 30.4  18.29 22.23 32.4
 28.55 18.04 12.54 10.29 34.81  9.94 25.56 19.49 38.01 26.41 11.24 48.27
 20.29 13.81 11.02 18.29 17.59 20.08 16.45  3.07 20.23 15.01 12.02 17.07
 26.86 25.28 14.73 10.51 17.92 27.2  22.76 17.29 19.44 16.66 10.07 32.68
 15.98 34.83 13.03 18.28 24.71 21.16 28.97 22.49  5.75 16.32 22.75 40.17
 27.28 12.03 21.01 12.46 11.35 15.38 44.3  22.42 20.92 15.36 20.49 25.21
 18.24 14.31 14.    7.25 38.07 23.95 25.71 17.31 29.93 10.65 12.43 24.08
 11.69 13.42 14.26 15.95 12.48 29.8   8.52 14.52 11.38 22.82 19.08 20.27
 11.17 12.26 18.26  8.51 10.33 14.15 16.   13.16 17.47 34.3  41.19 27.05
 16.43  8.35 18.64 11.87  9.78  7.51 14.07 13.13 17.26 24.55 19.77 29.85
 48.17 25.   13.39 16.49 21.5  12.66 16.21 13.

### Step-02: Import train_test_split from sklearn.model_selection

In [17]:
from sklearn.model_selection import train_test_split

In [18]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.30, random_state = 100)

In [19]:
x_train.head()

tip     sex smoker   day    time  size
189  4.0    Male    Yes   Sun  Dinner     3
145  1.5  Female     No  Thur   Lunch     2
74   2.2  Female     No   Sat  Dinner     2
234  3.0    Male    Yes   Sat  Dinner     2
198  2.0  Female    Yes  Thur   Lunch     2

In [20]:
print("x_train.head(): \n\n {} \n" .format(x_train.head()))
print("x_train.shape: {} \n" .format(x_train.shape))

x_train.head(): 

      tip     sex smoker   day    time  size
189  4.0    Male    Yes   Sun  Dinner     3
145  1.5  Female     No  Thur   Lunch     2
74   2.2  Female     No   Sat  Dinner     2
234  3.0    Male    Yes   Sat  Dinner     2
198  2.0  Female    Yes  Thur   Lunch     2 

x_train.shape: (170, 6) 



In [21]:
x_test.head()

tip     sex smoker   day    time  size
65   3.15    Male     No   Sat  Dinner     3
59   6.73    Male     No   Sat  Dinner     4
191  4.19  Female    Yes  Thur   Lunch     2
111  1.00  Female     No   Sat  Dinner     1
112  4.00    Male     No   Sun  Dinner     3

In [22]:
print("x_test.head(): \n\n {} \n" .format(x_test.head()))
print("x_test.shape: {} \n" .format(x_test.shape))

x_test.head(): 

       tip     sex smoker   day    time  size
65   3.15    Male     No   Sat  Dinner     3
59   6.73    Male     No   Sat  Dinner     4
191  4.19  Female    Yes  Thur   Lunch     2
111  1.00  Female     No   Sat  Dinner     1
112  4.00    Male     No   Sun  Dinner     3 

x_test.shape: (74, 6) 



In [23]:
y_train

array([23.1 ,  8.35, 14.73, 15.53, 13.  , 13.  , 43.11, 26.88, 21.7 ,
        9.78, 20.45, 16.04, 12.43,  7.51, 18.71, 10.34, 19.77, 27.2 ,
       27.18, 50.81, 11.59, 12.26, 13.28, 28.97, 16.47, 18.15, 14.52,
       12.9 , 15.95, 25.56, 20.92, 25.28, 18.64, 26.41, 30.4 , 11.69,
       12.16, 28.44,  8.52, 18.26,  9.6 , 13.27, 18.78, 10.27, 17.92,
       24.55,  5.75, 26.59, 28.15, 40.55, 10.07, 30.14, 15.42, 10.33,
       24.06, 21.16, 18.29, 16.82, 15.69, 10.34, 16.4 , 10.29, 16.27,
       31.27, 29.93, 14.26, 16.58,  8.77, 20.29, 14.78, 12.54, 31.85,
       10.63, 44.3 , 15.98, 20.69, 17.92, 24.08, 25.71, 40.17, 15.98,
       10.07, 13.51, 17.07, 25.29, 16.31,  9.68,  7.56, 17.51, 12.6 ,
       20.76, 12.02, 20.27, 38.73, 14.48, 16.99, 22.76, 24.27, 20.23,
       11.61, 34.63,  9.55, 20.49, 18.43, 26.86, 16.29, 16.21, 16.97,
        7.25, 18.69, 14.31, 31.71, 32.4 , 32.83, 13.39, 23.95, 38.01,
       12.69, 23.33, 18.29, 11.87, 15.36, 13.42, 21.01, 19.44, 23.17,
       22.12, 13.81,

In [24]:
print("y_train: \n\n {} \n" .format(y_train))
print("y_train.shape: {} \n" .format(y_train.shape))

y_train: 

 [23.1   8.35 14.73 15.53 13.   13.   43.11 26.88 21.7   9.78 20.45 16.04
 12.43  7.51 18.71 10.34 19.77 27.2  27.18 50.81 11.59 12.26 13.28 28.97
 16.47 18.15 14.52 12.9  15.95 25.56 20.92 25.28 18.64 26.41 30.4  11.69
 12.16 28.44  8.52 18.26  9.6  13.27 18.78 10.27 17.92 24.55  5.75 26.59
 28.15 40.55 10.07 30.14 15.42 10.33 24.06 21.16 18.29 16.82 15.69 10.34
 16.4  10.29 16.27 31.27 29.93 14.26 16.58  8.77 20.29 14.78 12.54 31.85
 10.63 44.3  15.98 20.69 17.92 24.08 25.71 40.17 15.98 10.07 13.51 17.07
 25.29 16.31  9.68  7.56 17.51 12.6  20.76 12.02 20.27 38.73 14.48 16.99
 22.76 24.27 20.23 11.61 34.63  9.55 20.49 18.43 26.86 16.29 16.21 16.97
  7.25 18.69 14.31 31.71 32.4  32.83 13.39 23.95 38.01 12.69 23.33 18.29
 11.87 15.36 13.42 21.01 19.44 23.17 22.12 13.81 15.48 32.9  18.04  8.51
 22.67 30.46 22.49 24.59 11.35 25.89 34.3  22.82 16.49 11.17 18.24 29.85
 19.08 13.03 16.32 14.15 16.43 11.24 20.29 25.21 27.05 17.82 17.78 14.83
 10.09 16.45  9.94 21.01 34.65 22.75 16

In [25]:
y_test

array([20.08, 48.27, 19.81,  7.25, 38.07, 12.66, 14.07, 21.5 , 12.46,
       32.68, 13.81, 18.35, 24.71, 34.83, 20.69, 45.35, 15.01, 12.03,
       16.66, 15.69, 22.23, 41.19, 29.03, 17.26, 29.8 , 20.53, 13.37,
       13.42, 12.76, 12.74, 17.59,  7.74, 23.68, 24.01, 15.06, 27.28,
       48.33, 17.47, 13.42, 17.46, 14.  , 11.38, 20.9 , 35.83, 10.51,
       28.17, 20.65, 30.06, 11.02, 19.65, 13.94, 17.31, 24.52,  8.58,
       28.55, 10.77, 39.42, 10.33, 19.49, 15.77, 34.81, 48.17, 13.16,
       25.  , 35.26, 21.58, 15.38, 17.81, 10.59, 10.65, 15.81, 16.93,
       12.48, 13.13])

In [26]:
print("y_test: \n\n {} \n" .format(y_test))
print("y_test.shape: {} \n" .format(y_test.shape))

y_test: 

 [20.08 48.27 19.81  7.25 38.07 12.66 14.07 21.5  12.46 32.68 13.81 18.35
 24.71 34.83 20.69 45.35 15.01 12.03 16.66 15.69 22.23 41.19 29.03 17.26
 29.8  20.53 13.37 13.42 12.76 12.74 17.59  7.74 23.68 24.01 15.06 27.28
 48.33 17.47 13.42 17.46 14.   11.38 20.9  35.83 10.51 28.17 20.65 30.06
 11.02 19.65 13.94 17.31 24.52  8.58 28.55 10.77 39.42 10.33 19.49 15.77
 34.81 48.17 13.16 25.   35.26 21.58 15.38 17.81 10.59 10.65 15.81 16.93
 12.48 13.13] 

y_test.shape: (74,) 



In [27]:
categorical_features = [features for features in x_train if x_train[features].dtype == "category"]
numerical_features = [features for features in x_train if x_train[features].dtype != "category"]

In [28]:
print("categorical features: {}" .format(categorical_features))

categorical features: ['sex', 'smoker', 'day', 'time']


In [29]:
print("numerical_features: {}" .format(numerical_features))

numerical_features: ['tip', 'size']


### Step-03: Import Pipeline from sklearn.pipeline

In [30]:
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

In [31]:
numerical_pipline = Pipeline (steps = [
     
    ("imputer", SimpleImputer(strategy = "median")),
    ("scaler", StandardScaler())
])

categorical_pipeline = Pipeline (steps = [
     
    ("imputer", SimpleImputer(strategy = "most_frequent")),
    ("encoder", OneHotEncoder())
])

In [32]:
preprocessor = ColumnTransformer(transformers = [
    
    ("numerical_pipline", numerical_pipline, numerical_features),
    ("categorical_pipeline", categorical_pipeline, categorical_features)
])

In [33]:
x_train_scaled = preprocessor.fit_transform(x_train)
x_test_scaled = preprocessor.transform(x_test)

In [34]:
x_train_scaled

array([[ 0.8824047 ,  0.52806002,  0.        , ...,  0.        ,
         1.        ,  0.        ],
       [-1.07634385, -0.58021409,  1.        , ...,  1.        ,
         0.        ,  1.        ],
       [-0.52789426, -0.58021409,  1.        , ...,  0.        ,
         1.        ,  0.        ],
       ...,
       [-1.46809357, -1.6884882 ,  1.        , ...,  0.        ,
         1.        ,  0.        ],
       [ 0.23993518, -0.58021409,  0.        , ...,  0.        ,
         1.        ,  0.        ],
       [-0.71593412, -0.58021409,  0.        , ...,  0.        ,
         1.        ,  0.        ]])

In [35]:
x_test_scaled

array([[ 0.21643019,  0.52806002,  0.        ,  1.        ,  1.        ,
         0.        ,  0.        ,  1.        ,  0.        ,  0.        ,
         1.        ,  0.        ],
       [ 3.02135813,  1.63633412,  0.        ,  1.        ,  1.        ,
         0.        ,  0.        ,  1.        ,  0.        ,  0.        ,
         1.        ,  0.        ],
       [ 1.03126959, -0.58021409,  1.        ,  0.        ,  0.        ,
         1.        ,  0.        ,  0.        ,  0.        ,  1.        ,
         0.        ,  1.        ],
       [-1.46809357, -1.6884882 ,  1.        ,  0.        ,  1.        ,
         0.        ,  0.        ,  1.        ,  0.        ,  0.        ,
         1.        ,  0.        ],
       [ 0.8824047 ,  0.52806002,  0.        ,  1.        ,  1.        ,
         0.        ,  0.        ,  0.        ,  1.        ,  0.        ,
         1.        ,  0.        ],
       [-0.29284443, -0.58021409,  0.        ,  1.        ,  1.        ,
         0.        ,  

### Step-04: Import RandomForestRegressor from sklearn.ensemble

In [36]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.svm import SVR

In [37]:
models = {
    "Random_Forest": RandomForestRegressor(),
    "Linear_Regression": LinearRegression(),
    "Decision_Tree_Regressor": DecisionTreeRegressor(),
    "Support_Vector_Regressor": SVR()
}

### Step-05: Import r2_score from sklearn.metrics

In [38]:
from sklearn.metrics import r2_score

In [39]:
def evaluate_models(x_train, x_test, y_train, y_test, models):
    report = {}
    for i in range(0,len(models)):
        model = list(models.values())[i]
        model.fit(x_train,y_train)
        y_pred = model.predict(x_test)
        accuracy = r2_score(y_test, y_pred)
        report[list(models.keys())[i]] = accuracy
    return report

In [40]:
evaluate_models(x_train_scaled, x_test_scaled, y_train, y_test, models)

{'Random_Forest': 0.6246774652528762,
 'Linear_Regression': 0.661237136402572,
 'Decision_Tree_Regressor': 0.48135737029680514,
 'Support_Vector_Regressor': 0.3764371693655191}

### Step-06: Import RandomizedSearchCV from sklearn.model_selection

In [41]:
from sklearn.model_selection import RandomizedSearchCV

In [42]:
random_forest = RandomForestRegressor()

In [43]:
parameters = {
    "max_depth": [3, 5, 10, None],
    "criterion": ["squared_error", "absolute_error", "friedman_mse", "poisson"],
    "n_estimators": [100, 200, 300]
}

In [44]:
randomized_cv = RandomizedSearchCV(random_forest, param_distributions = parameters, cv = 5, verbose = 3)

In [45]:
randomized_cv.fit(x_train_scaled, y_train)

Fitting 5 folds for each of 10 candidates, totalling 50 fits
[CV 1/5] END criterion=poisson, max_depth=10, n_estimators=300;, score=0.242 total time=   0.6s
[CV 2/5] END criterion=poisson, max_depth=10, n_estimators=300;, score=0.438 total time=   0.6s
[CV 3/5] END criterion=poisson, max_depth=10, n_estimators=300;, score=0.259 total time=   0.6s
[CV 4/5] END criterion=poisson, max_depth=10, n_estimators=300;, score=0.090 total time=   0.6s
[CV 5/5] END criterion=poisson, max_depth=10, n_estimators=300;, score=0.530 total time=   0.6s
[CV 1/5] END criterion=poisson, max_depth=None, n_estimators=200;, score=0.269 total time=   0.4s
[CV 2/5] END criterion=poisson, max_depth=None, n_estimators=200;, score=0.469 total time=   0.4s
[CV 3/5] END criterion=poisson, max_depth=None, n_estimators=200;, score=0.281 total time=   0.4s
[CV 4/5] END criterion=poisson, max_depth=None, n_estimators=200;, score=0.074 total time=   0.4s
[CV 5/5] END criterion=poisson, max_depth=None, n_estimators=200;, 

RandomizedSearchCV(cv=5, estimator=RandomForestRegressor(),
                   param_distributions={'criterion': ['squared_error',
                                                      'absolute_error',
                                                      'friedman_mse',
                                                      'poisson'],
                                        'max_depth': [3, 5, 10, None],
                                        'n_estimators': [100, 200, 300]},
                   verbose=3)

In [46]:
randomized_cv.best_params_

{'n_estimators': 100, 'max_depth': 3, 'criterion': 'absolute_error'}

In [47]:
randomized_cv.best_score_

0.37620905565748186

In [48]:
y_pred = randomized_cv.predict(x_test_scaled)

In [49]:
y_pred

array([19.42195, 29.6329 , 19.7951 ,  9.5761 , 19.4864 , 15.6485 ,
       15.6485 , 26.27975, 11.71795, 21.36575, 13.84745, 22.8087 ,
       20.55185, 29.36655, 28.9673 , 19.85085, 15.61255, 11.77035,
       19.1963 , 11.75545, 21.00705, 29.314  , 21.44   , 19.3265 ,
       26.37395, 28.54575, 13.9605 , 19.60805, 15.6749 , 15.07505,
       18.56105, 11.45925, 19.3283 , 24.37355, 19.0621 , 19.6191 ,
       32.31355, 19.18905, 12.00195, 16.5954 , 19.1424 , 13.624  ,
       19.77055, 22.0637 , 11.40685, 21.6683 , 19.49315, 17.92135,
       13.45905, 19.0621 , 19.17725, 19.36615, 19.60105, 12.32275,
       17.03375, 11.40685, 29.6329 , 13.624  , 19.44645, 15.644  ,
       28.91405, 28.9673 , 18.08175, 26.2018 , 28.93125, 19.3318 ,
       19.38425, 21.71815, 12.3651 , 11.7658 , 19.51715, 19.2218 ,
       15.46095, 13.84745])

In [50]:
print("Accuracy: {}" .format(r2_score(y_test, y_pred)))

Accuracy: 0.5285978685107495


In [51]:
random_forest = RandomForestRegressor(n_estimators = 300, max_depth = 3, criterion = "friedman_mse")

In [52]:
random_forest.fit(x_train_scaled, y_train)

RandomForestRegressor(criterion='friedman_mse', max_depth=3, n_estimators=300)

In [53]:
y_pred = random_forest.predict(x_test_scaled)

In [54]:
y_pred

array([21.02147826, 30.11270101, 20.42846045, 11.75209827, 21.40023327,
       16.07562012, 16.07562012, 25.85079468, 13.21103877, 22.2809024 ,
       13.89828819, 22.56445776, 20.81133821, 29.94130771, 28.82916034,
       22.46199249, 16.54762779, 13.33368282, 20.04417326, 13.41961216,
       21.07511774, 29.86771886, 23.55434187, 20.40468243, 26.82107756,
       29.25543184, 15.20239486, 20.54535827, 16.60277741, 14.66103001,
       20.35550382, 14.43308764, 20.27123382, 25.18973647, 20.07111186,
       20.60407221, 36.37051808, 19.81591448, 13.20944573, 17.68413082,
       20.27610414, 13.6108342 , 22.39480078, 23.46305379, 14.36288801,
       25.06441426, 20.98194585, 19.31423817, 15.15007306, 20.07111186,
       20.39945478, 20.04297504, 21.07874939, 12.71645531, 16.83028275,
       14.28283562, 30.11270101, 13.6108342 , 20.27123382, 16.37057464,
       28.86967142, 28.82916034, 18.90640979, 25.860844  , 28.94634615,
       20.04583354, 20.76984213, 20.52633982, 14.93107085, 13.04

In [55]:
print("Accuracy: {}" .format(r2_score(y_test, y_pred)))

Accuracy: 0.5683228099829858
