## # Machine Learning - Random Forest Classifier

### Step-01: Import all the libraries to perform Random Forest Classifier

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
import warnings
warnings.filterwarnings("ignore")

In [2]:
df = sns.load_dataset("tips")

In [3]:
df.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [4]:
print("df.head(): \n\n {} \n" .format(df.head()))
print("df.shape: {} \n" .format(df.shape))

df.head(): 

    total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4 

df.shape: (244, 7) 



In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype   
---  ------      --------------  -----   
 0   total_bill  244 non-null    float64 
 1   tip         244 non-null    float64 
 2   sex         244 non-null    category
 3   smoker      244 non-null    category
 4   day         244 non-null    category
 5   time        244 non-null    category
 6   size        244 non-null    int64   
dtypes: category(4), float64(2), int64(1)
memory usage: 7.4 KB


In [6]:
df.describe()

total_bill         tip        size
count  244.000000  244.000000  244.000000
mean    19.785943    2.998279    2.569672
std      8.902412    1.383638    0.951100
min      3.070000    1.000000    1.000000
25%     13.347500    2.000000    2.000000
50%     17.795000    2.900000    2.000000
75%     24.127500    3.562500    3.000000
max     50.810000   10.000000    6.000000

In [7]:
df.isnull().sum()

total_bill    0
tip           0
sex           0
smoker        0
day           0
time          0
size          0
dtype: int64

In [8]:
df["day"].unique()

['Sun', 'Sat', 'Thur', 'Fri']
Categories (4, object): ['Thur', 'Fri', 'Sat', 'Sun']

In [9]:
df["time"].unique()

['Dinner', 'Lunch']
Categories (2, object): ['Lunch', 'Dinner']

In [10]:
df["day"].value_counts()

Sat     87
Sun     76
Thur    62
Fri     19
Name: day, dtype: int64

In [11]:
df["time"].value_counts()

Dinner    176
Lunch      68
Name: time, dtype: int64

In [12]:
x = df.drop("time", axis = 1)
y = np.array(list(df["time"]))

In [13]:
x.head()

total_bill   tip     sex smoker  day  size
0       16.99  1.01  Female     No  Sun     2
1       10.34  1.66    Male     No  Sun     3
2       21.01  3.50    Male     No  Sun     3
3       23.68  3.31    Male     No  Sun     2
4       24.59  3.61  Female     No  Sun     4

In [14]:
print("x.head(): \n\n {} \n" .format(x.head()))
print("x.shape: {} \n" .format(x.shape))

x.head(): 

    total_bill   tip     sex smoker  day  size
0       16.99  1.01  Female     No  Sun     2
1       10.34  1.66    Male     No  Sun     3
2       21.01  3.50    Male     No  Sun     3
3       23.68  3.31    Male     No  Sun     2
4       24.59  3.61  Female     No  Sun     4 

x.shape: (244, 6) 



In [15]:
y

array(['Dinner', 'Dinner', 'Dinner', 'Dinner', 'Dinner', 'Dinner',
       'Dinner', 'Dinner', 'Dinner', 'Dinner', 'Dinner', 'Dinner',
       'Dinner', 'Dinner', 'Dinner', 'Dinner', 'Dinner', 'Dinner',
       'Dinner', 'Dinner', 'Dinner', 'Dinner', 'Dinner', 'Dinner',
       'Dinner', 'Dinner', 'Dinner', 'Dinner', 'Dinner', 'Dinner',
       'Dinner', 'Dinner', 'Dinner', 'Dinner', 'Dinner', 'Dinner',
       'Dinner', 'Dinner', 'Dinner', 'Dinner', 'Dinner', 'Dinner',
       'Dinner', 'Dinner', 'Dinner', 'Dinner', 'Dinner', 'Dinner',
       'Dinner', 'Dinner', 'Dinner', 'Dinner', 'Dinner', 'Dinner',
       'Dinner', 'Dinner', 'Dinner', 'Dinner', 'Dinner', 'Dinner',
       'Dinner', 'Dinner', 'Dinner', 'Dinner', 'Dinner', 'Dinner',
       'Dinner', 'Dinner', 'Dinner', 'Dinner', 'Dinner', 'Dinner',
       'Dinner', 'Dinner', 'Dinner', 'Dinner', 'Dinner', 'Lunch', 'Lunch',
       'Lunch', 'Lunch', 'Lunch', 'Lunch', 'Lunch', 'Lunch', 'Lunch',
       'Lunch', 'Lunch', 'Lunch', 'Lunch', 'Dinner'

In [16]:
print("y: \n\n {} \n" .format(y))
print("y.shape: {} \n" .format(y.shape))

y: 

 ['Dinner' 'Dinner' 'Dinner' 'Dinner' 'Dinner' 'Dinner' 'Dinner' 'Dinner'
 'Dinner' 'Dinner' 'Dinner' 'Dinner' 'Dinner' 'Dinner' 'Dinner' 'Dinner'
 'Dinner' 'Dinner' 'Dinner' 'Dinner' 'Dinner' 'Dinner' 'Dinner' 'Dinner'
 'Dinner' 'Dinner' 'Dinner' 'Dinner' 'Dinner' 'Dinner' 'Dinner' 'Dinner'
 'Dinner' 'Dinner' 'Dinner' 'Dinner' 'Dinner' 'Dinner' 'Dinner' 'Dinner'
 'Dinner' 'Dinner' 'Dinner' 'Dinner' 'Dinner' 'Dinner' 'Dinner' 'Dinner'
 'Dinner' 'Dinner' 'Dinner' 'Dinner' 'Dinner' 'Dinner' 'Dinner' 'Dinner'
 'Dinner' 'Dinner' 'Dinner' 'Dinner' 'Dinner' 'Dinner' 'Dinner' 'Dinner'
 'Dinner' 'Dinner' 'Dinner' 'Dinner' 'Dinner' 'Dinner' 'Dinner' 'Dinner'
 'Dinner' 'Dinner' 'Dinner' 'Dinner' 'Dinner' 'Lunch' 'Lunch' 'Lunch'
 'Lunch' 'Lunch' 'Lunch' 'Lunch' 'Lunch' 'Lunch' 'Lunch' 'Lunch' 'Lunch'
 'Lunch' 'Dinner' 'Dinner' 'Dinner' 'Dinner' 'Dinner' 'Dinner' 'Dinner'
 'Dinner' 'Dinner' 'Dinner' 'Dinner' 'Dinner' 'Dinner' 'Dinner' 'Dinner'
 'Dinner' 'Dinner' 'Dinner' 'Dinner' 'Dinner' 'Di

In [17]:
from sklearn.preprocessing import LabelEncoder

In [18]:
label_encoder = LabelEncoder()

In [19]:
y = label_encoder.fit_transform(y)

In [20]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0])

In [21]:
print("y: \n\n {} \n" .format(y))
print("y.shape: {} \n" .format(y.shape))

y: 

 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1
 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0] 

y.shape: (244,) 



### Step-02: Import train_test_split from sklearn.model_selection

In [22]:
from sklearn.model_selection import train_test_split

In [23]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.30, random_state = 100)

In [24]:
x_train.head()

total_bill  tip     sex smoker   day  size
189       23.10  4.0    Male    Yes   Sun     3
145        8.35  1.5  Female     No  Thur     2
74        14.73  2.2  Female     No   Sat     2
234       15.53  3.0    Male    Yes   Sat     2
198       13.00  2.0  Female    Yes  Thur     2

In [25]:
print("x_train.head(): \n\n {} \n" .format(x_train.head()))
print("x_train.shape: {} \n" .format(x_train.shape))

x_train.head(): 

      total_bill  tip     sex smoker   day  size
189       23.10  4.0    Male    Yes   Sun     3
145        8.35  1.5  Female     No  Thur     2
74        14.73  2.2  Female     No   Sat     2
234       15.53  3.0    Male    Yes   Sat     2
198       13.00  2.0  Female    Yes  Thur     2 

x_train.shape: (170, 6) 



In [26]:
x_test.head()

total_bill   tip     sex smoker   day  size
65        20.08  3.15    Male     No   Sat     3
59        48.27  6.73    Male     No   Sat     4
191       19.81  4.19  Female    Yes  Thur     2
111        7.25  1.00  Female     No   Sat     1
112       38.07  4.00    Male     No   Sun     3

In [27]:
print("x_test.head(): \n\n {} \n" .format(x_test.head()))
print("x_test.shape: {} \n" .format(x_test.shape))

x_test.head(): 

      total_bill   tip     sex smoker   day  size
65        20.08  3.15    Male     No   Sat     3
59        48.27  6.73    Male     No   Sat     4
191       19.81  4.19  Female    Yes  Thur     2
111        7.25  1.00  Female     No   Sat     1
112       38.07  4.00    Male     No   Sun     3 

x_test.shape: (74, 6) 



In [28]:
y_train

array([0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0])

In [29]:
print("y_train: \n\n {} \n" .format(y_train))
print("y_train.shape: {} \n" .format(y_train.shape))

y_train: 

 [0 1 0 0 1 1 1 0 0 1 0 0 1 1 1 0 0 1 0 0 0 1 0 0 1 0 1 0 1 0 0 0 1 0 0 1 1
 1 1 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1 0 0 0 1 1 0 1 0 0 1 1 0 0 0 0 0 0 0
 1 0 0 1 0 0 1 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 1 0 1 0 1 0 0 0 1 0 0 1 0 0 0 0 0 0 1 1 0 1 0 0 1 1 0 1
 1 0 0 0 1 0 0 0 1 0 0 0 0 0 1 0 1 1 0 0 0 0] 

y_train.shape: (170,) 



In [30]:
y_test

array([0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 1, 0])

In [31]:
print("y_test: \n\n {} \n" .format(y_test))
print("y_test.shape: {} \n" .format(y_test.shape))

y_test: 

 [0 0 1 0 0 0 0 0 0 1 0 0 1 1 0 0 0 0 1 0 0 1 0 0 1 1 0 1 0 1 0 0 0 0 0 0 0
 1 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 1 0 0 0 0 0 0 1 0 0 1 0] 

y_test.shape: (74,) 



In [32]:
categorical_features = [features for features in x_train if x_train[features].dtype == "category"]
numerical_features = [features for features in x_train if x_train[features].dtype != "category"]

In [33]:
print("categorical features: {}" .format(categorical_features))

categorical features: ['sex', 'smoker', 'day']


In [34]:
print("numerical_features: {}" .format(numerical_features))

numerical_features: ['total_bill', 'tip', 'size']


### Step-03: Import Pipeline from sklearn.pipeline

In [35]:
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

In [36]:
numerical_pipline = Pipeline (steps = [
     
    ("imputer", SimpleImputer(strategy = "median")),
    ("scaler", StandardScaler())
])

categorical_pipeline = Pipeline (steps = [
     
    ("imputer", SimpleImputer(strategy = "most_frequent")),
    ("encoder", OneHotEncoder())
])

In [37]:
preprocessor = ColumnTransformer(transformers = [
    
    ("numerical_pipline", numerical_pipline, numerical_features),
    ("categorical_pipeline", categorical_pipeline, categorical_features)
])

In [38]:
x_train_scaled = preprocessor.fit_transform(x_train)
x_test_scaled = preprocessor.transform(x_test)

In [39]:
x_train_scaled

array([[ 0.46651839,  0.8824047 ,  0.52806002, ...,  0.        ,
         1.        ,  0.        ],
       [-1.33541148, -1.07634385, -0.58021409, ...,  0.        ,
         0.        ,  1.        ],
       [-0.55600046, -0.52789426, -0.58021409, ...,  1.        ,
         0.        ,  0.        ],
       ...,
       [-1.98044129, -1.46809357, -1.6884882 , ...,  1.        ,
         0.        ,  0.        ],
       [ 0.06581805,  0.23993518, -0.58021409, ...,  1.        ,
         0.        ,  0.        ],
       [-0.51812939, -0.71593412, -0.58021409, ...,  0.        ,
         1.        ,  0.        ]])

In [40]:
x_test_scaled

array([[ 0.09758088,  0.21643019,  0.52806002,  0.        ,  1.        ,
         1.        ,  0.        ,  0.        ,  1.        ,  0.        ,
         0.        ],
       [ 3.54140481,  3.02135813,  1.63633412,  0.        ,  1.        ,
         1.        ,  0.        ,  0.        ,  1.        ,  0.        ,
         0.        ],
       [ 0.0645964 ,  1.03126959, -0.58021409,  1.        ,  0.        ,
         0.        ,  1.        ,  0.        ,  0.        ,  0.        ,
         1.        ],
       [-1.46979269, -1.46809357, -1.6884882 ,  1.        ,  0.        ,
         1.        ,  0.        ,  0.        ,  1.        ,  0.        ,
         0.        ],
       [ 2.29532449,  0.8824047 ,  0.52806002,  0.        ,  1.        ,
         1.        ,  0.        ,  0.        ,  0.        ,  1.        ,
         0.        ],
       [-0.80888147, -0.29284443, -0.58021409,  0.        ,  1.        ,
         1.        ,  0.        ,  0.        ,  0.        ,  1.        ,
         0.   

### Step-04: Import RandomForestClassifier from sklearn.ensemble

In [42]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC

In [44]:
models = {
    "Random_Forest": RandomForestClassifier(),
    "Logistic_Regression": LogisticRegression(),
    "Decision_Tree_Classifier": DecisionTreeClassifier(),
    "Support_Vector_Classifier": SVC()
}

### Step-05: Import accuracy_score from sklearn.metrics

In [45]:
from sklearn.metrics import accuracy_score

In [47]:
def evaluate_models(x_train, x_test, y_train, y_test, models):
    report = {}
    for i in range(0,len(models)):
        model = list(models.values())[i]
        model.fit(x_train,y_train)
        y_pred = model.predict(x_test)
        accuracy = accuracy_score(y_test, y_pred)
        report[list(models.keys())[i]] = accuracy
    return report

In [48]:
evaluate_models(x_train_scaled, x_test_scaled, y_train, y_test, models)

{'Random_Forest': 0.972972972972973,
 'Logistic_Regression': 0.9594594594594594,
 'Decision_Tree_Classifier': 0.9594594594594594,
 'Support_Vector_Classifier': 0.9324324324324325}

### Step-06: Import RandomizedSearchCV from sklearn.model_selection

In [49]:
from sklearn.model_selection import RandomizedSearchCV

In [51]:
random_forest = RandomForestClassifier()

In [52]:
parameters = {
    "max_depth": [3, 5, 10, None],
    "criterion": ["entropy", "gini"],
    "n_estimators": [100, 200, 300]
}

In [53]:
randomized_cv = RandomizedSearchCV(random_forest, param_distributions = parameters, scoring = "accuracy", cv = 5, verbose = 3)

In [54]:
randomized_cv.fit(x_train_scaled, y_train)

Fitting 5 folds for each of 10 candidates, totalling 50 fits
[CV 1/5] END criterion=gini, max_depth=None, n_estimators=200;, score=0.971 total time=   0.4s
[CV 2/5] END criterion=gini, max_depth=None, n_estimators=200;, score=0.941 total time=   0.4s
[CV 3/5] END criterion=gini, max_depth=None, n_estimators=200;, score=0.941 total time=   0.4s
[CV 4/5] END criterion=gini, max_depth=None, n_estimators=200;, score=1.000 total time=   0.4s
[CV 5/5] END criterion=gini, max_depth=None, n_estimators=200;, score=0.941 total time=   0.4s
[CV 1/5] END criterion=gini, max_depth=None, n_estimators=100;, score=0.971 total time=   0.2s
[CV 2/5] END criterion=gini, max_depth=None, n_estimators=100;, score=0.912 total time=   0.2s
[CV 3/5] END criterion=gini, max_depth=None, n_estimators=100;, score=0.941 total time=   0.2s
[CV 4/5] END criterion=gini, max_depth=None, n_estimators=100;, score=1.000 total time=   0.2s
[CV 5/5] END criterion=gini, max_depth=None, n_estimators=100;, score=0.941 total ti

RandomizedSearchCV(cv=5, estimator=RandomForestClassifier(),
                   param_distributions={'criterion': ['entropy', 'gini'],
                                        'max_depth': [3, 5, 10, None],
                                        'n_estimators': [100, 200, 300]},
                   scoring='accuracy', verbose=3)

In [55]:
randomized_cv.best_params_

{'n_estimators': 200, 'max_depth': 3, 'criterion': 'entropy'}

In [56]:
randomized_cv.best_score_

0.9705882352941175

In [57]:
random_forest = RandomForestClassifier(n_estimators = 200, max_depth = 3, criterion = "entropy")

In [58]:
random_forest.fit(x_train_scaled, y_train)

RandomForestClassifier(criterion='entropy', max_depth=3, n_estimators=200)

In [59]:
y_pred = random_forest.predict(x_test_scaled)

In [60]:
y_pred

array([0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 1, 0])

In [63]:
print("Accuracy: {}" .format(accuracy_score(y_test, y_pred)))

Accuracy: 0.9594594594594594
