In [1]:
import numpy

In [3]:
# Numpy - Sorting, Counting Function

In [2]:
array_01 = numpy.array([18, 90, 45, 12, 30])

In [10]:
array_01 = numpy.sort(array_01)

In [12]:
array_01

array([12, 18, 30, 45, 90])

In [11]:
numpy.searchsorted(array_01, 25)

2

In [14]:
array_02 = numpy.array([0, 12, 25, 60, 45, 0, 0, 0, 60])

In [17]:
numpy.count_nonzero(array_02)

5

In [15]:
numpy.nonzero(array_02)

(array([1, 2, 3, 4, 8]),)

In [16]:
numpy.where(array_01 >= 30)

(array([2, 3, 4]),)

In [18]:
numpy.extract(array_01 >= 40, array_01)

array([45, 90])

In [19]:
# Numpy - Byte Swapping

In [20]:
array_01.byteswap()

array([ 864691128455135232, 1297036692682702848, 2161727821137838080,
       3242591731706757120, 6485183463413514240])

In [22]:
# Numpy - Linear Algebra

In [23]:
array_01 = numpy.random.randint(0,10,(3,3))

In [24]:
array_02 = numpy.random.randint(0,10,(3,3))

In [25]:
array_01

array([[1, 3, 1],
       [9, 3, 5],
       [6, 7, 1]])

In [26]:
array_02

array([[6, 6, 3],
       [5, 3, 6],
       [7, 3, 0]])

In [27]:
numpy.dot(array_01, array_02)

array([[ 28,  18,  21],
       [104,  78,  45],
       [ 78,  60,  60]])

In [28]:
array_01 @ array_02

array([[ 28,  18,  21],
       [104,  78,  45],
       [ 78,  60,  60]])