In [1]:
 import numpy

In [26]:
# Numpy - Array Manipulation

In [2]:
array_01 = numpy.random.randint(1,10, (3,4))

In [3]:
array_01

array([[1, 2, 9, 5],
       [4, 3, 9, 3],
       [7, 5, 2, 4]])

In [4]:
array_01.reshape(2,6)

array([[1, 2, 9, 5, 4, 3],
       [9, 3, 7, 5, 2, 4]])

In [6]:
array_01.reshape(6,2)

array([[1, 2],
       [9, 5],
       [4, 3],
       [9, 3],
       [7, 5],
       [2, 4]])

In [7]:
array_01.reshape(2, -2)

array([[1, 2, 9, 5, 4, 3],
       [9, 3, 7, 5, 2, 4]])

In [11]:
array_01.T

array([[1, 4, 7],
       [2, 3, 5],
       [9, 9, 2],
       [5, 3, 4]])

In [12]:
array_01.flatten()

array([1, 2, 9, 5, 4, 3, 9, 3, 7, 5, 2, 4])

In [13]:
array_02 = numpy.array([1,2,3,4,5])

In [16]:
numpy.expand_dims(array_02, axis = 0)

array([[1, 2, 3, 4, 5]])

In [17]:
numpy.expand_dims(array_02, axis = 1)

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [18]:
array_03 = numpy.array([[1], [2], [3], [4], [5]])

In [19]:
array_03

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [20]:
array_03.squeeze()

array([1, 2, 3, 4, 5])

In [21]:
array_02

array([1, 2, 3, 4, 5])

In [22]:
numpy.roll(array_02, 3)

array([3, 4, 5, 1, 2])

In [24]:
numpy.diag(array_02)

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [25]:
numpy.repeat(array_02, 3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4, 5, 5, 5])

In [27]:
# Numpy - Binary Operations

In [28]:
array_01 = numpy.random.randint(1,10, (3,3))

In [29]:
array_02 = numpy.random.randint(1, 10, (3,3))

In [30]:
array_01

array([[8, 9, 3],
       [1, 1, 4],
       [1, 5, 6]])

In [31]:
array_02

array([[1, 7, 8],
       [7, 8, 7],
       [9, 8, 9]])

In [32]:
array_01 & array_02

array([[0, 1, 0],
       [1, 0, 4],
       [1, 0, 0]])

In [33]:
array_01 | array_02

array([[ 9, 15, 11],
       [ 7,  9,  7],
       [ 9, 13, 15]])

In [34]:
~array_01

array([[ -9, -10,  -4],
       [ -2,  -2,  -5],
       [ -2,  -6,  -7]])

In [35]:
array_01 + array_02

array([[ 9, 16, 11],
       [ 8,  9, 11],
       [10, 13, 15]])

In [36]:
array_01 - array_02

array([[ 7,  2, -5],
       [-6, -7, -3],
       [-8, -3, -3]])

In [37]:
array_01 * array_02

array([[ 8, 63, 24],
       [ 7,  8, 28],
       [ 9, 40, 54]])

In [39]:
array_01 % array_02

array([[0, 2, 3],
       [1, 1, 4],
       [1, 5, 6]])

In [41]:
array_01 ** 2

array([[64, 81,  9],
       [ 1,  1, 16],
       [ 1, 25, 36]])

In [42]:
# Numpy - String Functions

In [43]:
array_01 = numpy.array(["balaji", "srinivas", "rahul", "vinay"])

In [44]:
array_01

array(['balaji', 'srinivas', 'rahul', 'vinay'], dtype='<U8')

In [45]:
numpy.char.upper(array_01)

array(['BALAJI', 'SRINIVAS', 'RAHUL', 'VINAY'], dtype='<U8')

In [46]:
numpy.char.title(array_01)

array(['Balaji', 'Srinivas', 'Rahul', 'Vinay'], dtype='<U8')

In [47]:
numpy.char.lower(array_01)

array(['balaji', 'srinivas', 'rahul', 'vinay'], dtype='<U8')

In [48]:
numpy.char.capitalize(array_01)

array(['Balaji', 'Srinivas', 'Rahul', 'Vinay'], dtype='<U8')

In [49]:
# Numpy - Mathematical Functions

In [50]:
array_01 = numpy.random.randint(1,10, (3,3))

In [51]:
array_01

array([[3, 2, 4],
       [4, 9, 4],
       [5, 8, 4]])

In [52]:
numpy.sin(array_01)

array([[ 0.14112001,  0.90929743, -0.7568025 ],
       [-0.7568025 ,  0.41211849, -0.7568025 ],
       [-0.95892427,  0.98935825, -0.7568025 ]])

In [53]:
numpy.cos(array_01)

array([[-0.9899925 , -0.41614684, -0.65364362],
       [-0.65364362, -0.91113026, -0.65364362],
       [ 0.28366219, -0.14550003, -0.65364362]])

In [54]:
numpy.tan(array_01)

array([[-0.14254654, -2.18503986,  1.15782128],
       [ 1.15782128, -0.45231566,  1.15782128],
       [-3.38051501, -6.79971146,  1.15782128]])

In [55]:
numpy.sinh(array_01)

array([[1.00178749e+01, 3.62686041e+00, 2.72899172e+01],
       [2.72899172e+01, 4.05154190e+03, 2.72899172e+01],
       [7.42032106e+01, 1.49047883e+03, 2.72899172e+01]])

In [56]:
numpy.cosh(array_01)

array([[1.00676620e+01, 3.76219569e+00, 2.73082328e+01],
       [2.73082328e+01, 4.05154203e+03, 2.73082328e+01],
       [7.42099485e+01, 1.49047916e+03, 2.73082328e+01]])

In [57]:
numpy.tanh(array_01)

array([[0.99505475, 0.96402758, 0.9993293 ],
       [0.9993293 , 0.99999997, 0.9993293 ],
       [0.9999092 , 0.99999977, 0.9993293 ]])

In [58]:
numpy.log10(array_01)

array([[0.47712125, 0.30103   , 0.60205999],
       [0.60205999, 0.95424251, 0.60205999],
       [0.69897   , 0.90308999, 0.60205999]])

In [59]:
numpy.exp(array_01)

array([[2.00855369e+01, 7.38905610e+00, 5.45981500e+01],
       [5.45981500e+01, 8.10308393e+03, 5.45981500e+01],
       [1.48413159e+02, 2.98095799e+03, 5.45981500e+01]])

In [60]:
numpy.sqrt(array_01)

array([[1.73205081, 1.41421356, 2.        ],
       [2.        , 3.        , 2.        ],
       [2.23606798, 2.82842712, 2.        ]])

In [61]:
numpy.power(array_01, 2)

array([[ 9,  4, 16],
       [16, 81, 16],
       [25, 64, 16]])

In [62]:
numpy.mean(array_01)

4.777777777777778

In [63]:
numpy.median(array_01)

4.0

In [64]:
numpy.std(array_01)

2.1487866228681907

In [66]:
numpy.var(array_01)

4.617283950617283

In [67]:
numpy.max(array_01)

9

In [68]:
numpy.min(array_01)

2