In [1]:
import numpy

In [2]:
list_01 = [10, 20, 30, 40, 50]

In [3]:
array_01 = numpy.array(list_01)

In [4]:
array_01

array([10, 20, 30, 40, 50])

In [5]:
type(array_01)

numpy.ndarray

In [6]:
list_02 = [[10, 20], [30, 40]]

In [7]:
array_02 = numpy.array(list_02)

In [8]:
array_02

array([[10, 20],
       [30, 40]])

In [9]:
type(array_02)

numpy.ndarray

In [10]:
numpy.asarray(list_01)

array([10, 20, 30, 40, 50])

In [11]:
numpy.asanyarray(list_01)

array([10, 20, 30, 40, 50])

In [12]:
matrix_01 = numpy.matrix([[10, 20], [30, 40]])

In [13]:
matrix_01

matrix([[10, 20],
        [30, 40]])

In [14]:
type(matrix_01)

numpy.matrix

In [15]:
numpy.asanyarray(matrix_01)

matrix([[10, 20],
        [30, 40]])

In [16]:
numpy.asarray(matrix_01)

array([[10, 20],
       [30, 40]])

In [17]:
numpy.array(matrix_01)

array([[10, 20],
       [30, 40]])

In [18]:
# matrix is a sub-set of array

In [19]:
list_01 = [10, 20, 30, 40, 50]

In [20]:
array_01 = numpy.array(list_01)

In [21]:
array_02 = array_01

In [24]:
array_01

array([10, 20, 30, 40, 50])

In [25]:
array_02

array([10, 20, 30, 40, 50])

In [26]:
array_01[4] = 60

In [29]:
# Shallow Copy

In [27]:
array_01

array([10, 20, 30, 40, 60])

In [28]:
array_02

array([10, 20, 30, 40, 60])

In [30]:
# Deep Copy

In [31]:
array_03 = numpy.copy(array_01)

In [32]:
array_01

array([10, 20, 30, 40, 60])

In [33]:
array_03

array([10, 20, 30, 40, 60])

In [34]:
array_01[4] = 70

In [37]:
array_01

array([10, 20, 30, 40, 70])

In [36]:
array_03

array([10, 20, 30, 40, 60])

In [38]:
array_03[4] = 80

In [39]:
array_03

array([10, 20, 30, 40, 80])

In [40]:
array_01

array([10, 20, 30, 40, 70])

In [41]:
numpy.fromfunction(lambda i, j : i == j, (3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [42]:
numpy.fromfunction(lambda i, j : i + j, (3,3))

array([[0., 1., 2.],
       [1., 2., 3.],
       [2., 3., 4.]])

In [44]:
iterable = (i * i for i in range(5))

In [45]:
numpy.fromiter(iterable, int)

array([ 0,  1,  4,  9, 16])

In [48]:
numpy.fromstring("10 20 30 40 50", sep = " ")

array([10., 20., 30., 40., 50.])

In [49]:
numpy.fromstring("10, 20, 30, 40, 50", sep = ",")

array([10., 20., 30., 40., 50.])

In [50]:
# Python Numpy - Data Types

In [51]:
list_01 = [10, 20, 30, 40, 50]

In [52]:
array_01 = numpy.array(list_01)

In [53]:
array_01.ndim

1

In [54]:
array_01.size

5

In [55]:
array_01.shape

(5,)

In [57]:
list_02 = [[10, 10], [20, 20], [30, 30]]

In [58]:
array_02 = numpy.array(list_02)

In [59]:
array_02.ndim

2

In [60]:
array_02.size

6

In [61]:
array_02.shape

(3, 2)

In [62]:
array_01.dtype

dtype('int64')

In [63]:
array_02.dtype

dtype('int64')

In [64]:
list_03 = [4.8, 5.6 , 7.8, 9.0]

In [65]:
array_03 = numpy.array(list_03)

In [66]:
array_03.dtype

dtype('float64')

In [69]:
list(range(5))

[0, 1, 2, 3, 4]

In [71]:
numpy.arange(0, 5)

array([0, 1, 2, 3, 4])

In [72]:
numpy.arange(0, 5, 0.5)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [73]:
numpy.arange(2.4, 5.8, 0.4)

array([2.4, 2.8, 3.2, 3.6, 4. , 4.4, 4.8, 5.2, 5.6])

In [1]:
import numpy
import pandas

In [10]:
numpy.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [11]:
numpy.logspace(1, 2, 5, base = 10)

array([ 10.        ,  17.7827941 ,  31.6227766 ,  56.23413252,
       100.        ])

In [13]:
numpy.zeros(5)

array([0., 0., 0., 0., 0.])

In [14]:
numpy.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [16]:
numpy.zeros((5,5,5))

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [17]:
numpy.ones(3)

array([1., 1., 1.])

In [18]:
numpy.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [19]:
numpy.ones((3,3,3))

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [38]:
numpy.random.randn(3,3)

array([[-1.8889215 , -0.61748227, -0.94959337],
       [-0.03118375, -1.40625971,  0.71924652],
       [ 0.41657458, -1.89445092,  0.12510936]])

In [39]:
numpy.random.rand(3,4)

array([[5.94379006e-04, 9.67213616e-01, 9.32141255e-02, 5.42148407e-01],
       [4.30578607e-01, 5.87926256e-01, 1.68377900e-01, 2.62223962e-02],
       [6.27444086e-03, 9.00366776e-02, 4.76801353e-01, 6.18132131e-01]])

In [40]:
numpy.random.randint(1,10, (5,5))

array([[1, 3, 4, 2, 8],
       [6, 3, 8, 4, 3],
       [8, 5, 6, 9, 9],
       [3, 6, 2, 3, 5],
       [7, 6, 5, 8, 8]])

In [41]:
pandas.DataFrame(numpy.random.randint(1,10, (5,5)))

0  1  2  3  4
0  7  4  8  6  2
1  7  7  3  9  3
2  6  6  1  9  8
3  2  3  6  6  5
4  8  8  8  6  4

In [43]:
pandas.DataFrame(numpy.random.randint(1,10, (5,5))).to_csv("array_01.csv")

In [44]:
array_01 = numpy.random.randint(1,10, (5,5))

In [45]:
array_01 

array([[4, 3, 6, 3, 9],
       [7, 6, 6, 1, 4],
       [9, 8, 3, 3, 5],
       [3, 5, 4, 1, 2],
       [3, 2, 7, 5, 4]])

In [46]:
array_01[0:5, 1]

array([3, 6, 8, 5, 2])

In [47]:
array_01[2:4, (1,2)]

array([[8, 3],
       [5, 4]])

In [49]:
array_01[0][0] = 5

In [50]:
array_01

array([[5, 3, 6, 3, 9],
       [7, 6, 6, 1, 4],
       [9, 8, 3, 3, 5],
       [3, 5, 4, 1, 2],
       [3, 2, 7, 5, 4]])

In [51]:
array_01 = numpy.random.randint(1,10,(3,4))

In [52]:
array_01

array([[6, 2, 7, 1],
       [5, 3, 1, 8],
       [4, 5, 5, 8]])

In [54]:
array_01.reshape(6,2)

array([[6, 2],
       [7, 1],
       [5, 3],
       [1, 8],
       [4, 5],
       [5, 8]])

In [75]:
# Python Numpy - Mathematical Operations

In [72]:
array_01 = numpy.random.randint(1,6,(3,3))

In [56]:
array_02 = numpy.random.randint(1,6,(3,3))

In [57]:
array_01

array([[5, 2, 2],
       [2, 4, 2],
       [1, 2, 1]])

In [58]:
array_02

array([[4, 4, 5],
       [1, 1, 3],
       [4, 4, 4]])

In [59]:
array_01 + array_02

array([[9, 6, 7],
       [3, 5, 5],
       [5, 6, 5]])

In [60]:
array_01 - array_02

array([[ 1, -2, -3],
       [ 1,  3, -1],
       [-3, -2, -3]])

In [61]:
array_01 * array_02

array([[20,  8, 10],
       [ 2,  4,  6],
       [ 4,  8,  4]])

In [62]:
array_01 / array_02

array([[1.25      , 0.5       , 0.4       ],
       [2.        , 4.        , 0.66666667],
       [0.25      , 0.5       , 0.25      ]])

In [63]:
array_01 @ array_02

array([[30, 30, 39],
       [20, 20, 30],
       [10, 10, 15]])

In [64]:
array_01 ** 2

array([[25,  4,  4],
       [ 4, 16,  4],
       [ 1,  4,  1]])

In [69]:
array_03 = numpy.eye(3, dtype = int)

In [70]:
array_01 @ array_03

array([[5, 2, 2],
       [2, 4, 2],
       [1, 2, 1]])

In [74]:
array_01

array([[3, 1, 2],
       [1, 5, 2],
       [3, 3, 1]])

In [73]:
array_01 + array_03

array([[4, 1, 2],
       [1, 6, 2],
       [3, 3, 2]])

In [76]:
# Numpy Python - Broadcasting

In [85]:
list_01 = [[1, 2, 3]]

In [86]:
array_01 = numpy.zeros((3,3), dtype = int)

In [87]:
row_01 = numpy.array(list_01)

In [88]:
array_01 + row_01

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [89]:
col_01 = numpy.array(list_01).T

In [91]:
array_01 + col_01

array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

In [92]:
array_01 = numpy.random.randint(1,11,(3,3))

In [93]:
array_01

array([[ 4,  3,  1],
       [ 8,  3,  2],
       [ 9,  3, 10]])

In [94]:
numpy.sqrt(array_01)

array([[2.        , 1.73205081, 1.        ],
       [2.82842712, 1.73205081, 1.41421356],
       [3.        , 1.73205081, 3.16227766]])

In [95]:
numpy.exp(array_01)

array([[5.45981500e+01, 2.00855369e+01, 2.71828183e+00],
       [2.98095799e+03, 2.00855369e+01, 7.38905610e+00],
       [8.10308393e+03, 2.00855369e+01, 2.20264658e+04]])

In [96]:
numpy.log10(array_01)

array([[0.60205999, 0.47712125, 0.        ],
       [0.90308999, 0.47712125, 0.30103   ],
       [0.95424251, 0.47712125, 1.        ]])