In [7]:
# Basics of Numpy

In [1]:
import numpy as np

In [38]:
a = np.array([1,2,3,4,5], dtype = "int32")
print(a)

[1 2 3 4 5]


In [39]:
b = np.array([[1,2,3,4,5],[6,7,8,9,10]], dtype = "int32")
print(b)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [50]:
def print_dimension(a,b) :
    print("a.ndim = " + str(a.ndim))
    print("b.ndim = " + str(b.ndim))

In [51]:
def print_size(a,b) :
    print("a.size = " + str(a.size))
    print("b.size = " + str(b.size))

In [52]:
def print_shape(a,b) :
    print("a.shape = " + str(a.shape))
    print("b.shape = " + str(b.shape))

In [53]:
def print_dtype(a,b) :
    print("a.dtype = " + str(a.dtype))
    print("b.dtype = " + str(b.dtype))

In [54]:
def print_itemsize(a,b) :
    print("a.itemsize = " + str(a.itemsize))
    print("b.itemsize = " + str(b.itemsize))

In [90]:
def print_memory(a,b) :
    print("Total memory size of array 'a' : " + str(a.nbytes))
    print("Total memory size of array 'b' : " + str(b.nbytes))

In [8]:
# Accessing Elements From Arrays

In [9]:
a[4]

5

In [10]:
b[1,4]

10

In [11]:
b[1][4]

10

In [12]:
b[0][1:4:1]

array([2, 3, 4])

In [19]:
b[1,:]

array([ 6,  7,  8,  9, 10])

In [20]:
b[:,1]

array([2, 7])

In [22]:
b[:,1:4:2]

array([[2, 4],
       [7, 9]])

In [28]:
b[0:2:1,1:4:2]

array([[2, 4],
       [7, 9]])

In [45]:
# Types of Arrays

In [69]:
a = np.array([1,2,3,4,5])
b = np.matrix([1,2,3,4,5])

In [70]:
print(a)
print(b)

[1 2 3 4 5]
[[1 2 3 4 5]]


In [71]:
print_dimension(a,b)

a.ndim = 1
b.ndim = 2


In [72]:
print_size(a,b)

a.size = 5
b.size = 5


In [81]:
print_shape(a,b)

a.shape = (5,)
b.shape = (1, 5)


In [82]:
print_itemsize(a,b)

a.itemsize = 8
b.itemsize = 8


In [91]:
print_memory(a,b)

Total memory size of array 'a' : 40
Total memory size of array 'b' : 40


In [84]:
np.asarray(b)

array([[1, 2, 3, 4, 5]])

In [86]:
np.asanyarray(b)

matrix([[1, 2, 3, 4, 5]])

In [92]:
# 3-Dimensional Array

In [96]:
a = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(a)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [97]:
a[0][1][0]

3

In [98]:
a[1][0][1]

6

In [99]:
a[:,:,1]

array([[2, 4],
       [6, 8]])

In [100]:
a[1,:,:]

array([[5, 6],
       [7, 8]])

In [101]:
a[:,0,:]

array([[1, 2],
       [5, 6]])

In [111]:
# NumPy - Zeros & Ones Function

In [102]:
np.zeros((3,3,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [103]:
np.ones((3,3,3))

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [104]:
np.eye(3, dtype = "int64")

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [105]:
np.zeros((5))

array([0., 0., 0., 0., 0.])

In [107]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [109]:
np.ones((5))

array([1., 1., 1., 1., 1.])

In [110]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [112]:
# NumPy - Linspace & Logspace Function

In [115]:
np.linspace(start = 1, stop = 10, num = 20)

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [118]:
np.logspace(start = 1, stop = 2, num = 5, base = 10)

array([ 10.        ,  17.7827941 ,  31.6227766 ,  56.23413252,
       100.        ])

In [129]:
# NumPy - From Function, Iter, String

In [120]:
np.fromfunction(lambda i, j : i == j, shape = (3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [124]:
np.fromfunction(lambda i, j : i * j, shape = (3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [125]:
iterable = (i * i for i in range(5))

In [126]:
np.fromiter(iterable, dtype = "int64")

array([ 0,  1,  4,  9, 16])

In [127]:
np.fromstring("1 2 3 4 5", dtype = "int64", sep = " ")

array([1, 2, 3, 4, 5])

In [128]:
np.fromstring("1,2,3,4,5", dtype = "int64", sep = ",")

array([1, 2, 3, 4, 5])

In [130]:
# NumPy - Rand, Randint

In [131]:
a = np.random.rand(5,5)

In [132]:
print(a)

[[0.49554246 0.99895479 0.63632195 0.09074537 0.64226454]
 [0.14855203 0.05282557 0.65385411 0.4675957  0.40834175]
 [0.29426697 0.07167946 0.21154335 0.1953416  0.89520413]
 [0.08105944 0.17000139 0.81714255 0.73799471 0.14759025]
 [0.73949487 0.91993379 0.15722192 0.89298881 0.63429449]]


In [133]:
b = np.random.randn(5,5)

In [134]:
print(b)

[[ 1.58211617  0.22151587  0.43669558 -1.12523322 -0.18882681]
 [ 0.07410226 -0.82853453  1.24057004  0.16944587 -0.61779026]
 [-0.44222821 -0.11161402 -1.3499777   0.10861481  1.05910774]
 [-0.11619151 -0.81539559  0.14342669 -0.26613476 -0.82855713]
 [-0.40744328 -0.67463325 -0.17784122  1.69950667  0.61528264]]


In [156]:
# NumPy - Mathematical Operations

In [138]:
array_01 = np.random.randint(low = 0, high = 10, size = (3,3), dtype = "int64")

In [139]:
print(array_01)

[[7 5 7]
 [0 1 4]
 [5 7 7]]


In [140]:
array_02 = np.random.randint(low = 0, high = 10, size = (3,3), dtype = "int64")

In [141]:
print(array_02)

[[8 5 2]
 [2 9 6]
 [9 7 7]]


In [142]:
array_01 + array_02

array([[15, 10,  9],
       [ 2, 10, 10],
       [14, 14, 14]])

In [143]:
array_01 - array_02

array([[-1,  0,  5],
       [-2, -8, -2],
       [-4,  0,  0]])

In [144]:
array_01 * array_02

array([[56, 25, 14],
       [ 0,  9, 24],
       [45, 49, 49]])

In [145]:
array_01 / array_02

array([[0.875     , 1.        , 3.5       ],
       [0.        , 0.11111111, 0.66666667],
       [0.55555556, 1.        , 1.        ]])

In [146]:
array_01 @ array_02

array([[129, 129,  93],
       [ 38,  37,  34],
       [117, 137, 101]])

In [147]:
import pandas as pd
import numpy as np
import seaborn as sns

In [148]:
df_01 = pd.DataFrame(np.random.randint(0,9,(5,5)))

In [151]:
df_01

0  1  2  3  4
0  6  6  0  6  7
1  5  5  8  4  8
2  2  4  8  4  0
3  0  0  6  7  6
4  5  8  2  8  3

In [152]:
df_01.describe()

0         1        2         3         4
count  5.00000  5.000000  5.00000  5.000000  5.000000
mean   3.60000  4.600000  4.80000  5.800000  4.800000
std    2.50998  2.966479  3.63318  1.788854  3.271085
min    0.00000  0.000000  0.00000  4.000000  0.000000
25%    2.00000  4.000000  2.00000  4.000000  3.000000
50%    5.00000  5.000000  6.00000  6.000000  6.000000
75%    5.00000  6.000000  8.00000  7.000000  7.000000
max    6.00000  8.000000  8.00000  8.000000  8.000000

In [153]:
df_01[1]

0    6
1    5
2    4
3    0
4    8
Name: 1, dtype: int64

In [154]:
df_01[[2, 4]]

2  4
0  0  7
1  8  8
2  8  0
3  6  6
4  2  3

In [155]:
df_01.to_csv("array_02.csv")

In [157]:
# NumPy - Broadcasting

In [158]:
array_01 = np.zeros((3,3), dtype = "int64")

In [160]:
print(array_01)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [161]:
row_01 = np.array([1,2,3])

In [162]:
print(row_01)

[1 2 3]


In [163]:
array_01 + row_01

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [171]:
col_01 = np.array([[1,2,3]]).T

In [175]:
print(col_01)

[[1]
 [2]
 [3]]


In [176]:
array_01 + col_01

array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

In [177]:
array_01 = np.random.randint(0,10,(3,3))

In [178]:
print(array_01)

[[8 9 7]
 [2 3 8]
 [5 2 0]]


In [179]:
np.sqrt(array_01)

array([[2.82842712, 3.        , 2.64575131],
       [1.41421356, 1.73205081, 2.82842712],
       [2.23606798, 1.41421356, 0.        ]])

In [180]:
np.exp(array_01)

array([[2.98095799e+03, 8.10308393e+03, 1.09663316e+03],
       [7.38905610e+00, 2.00855369e+01, 2.98095799e+03],
       [1.48413159e+02, 7.38905610e+00, 1.00000000e+00]])

In [181]:
np.log10(array_01)

/tmp/ipykernel_382/96914493.py:1: RuntimeWarning: divide by zero encountered in log10
  np.log10(array_01)


array([[0.90308999, 0.95424251, 0.84509804],
       [0.30103   , 0.47712125, 0.90308999],
       [0.69897   , 0.30103   ,       -inf]])

In [182]:
np.sin(array_01)

array([[ 0.98935825,  0.41211849,  0.6569866 ],
       [ 0.90929743,  0.14112001,  0.98935825],
       [-0.95892427,  0.90929743,  0.        ]])

In [183]:
np.cos(array_01)

array([[-0.14550003, -0.91113026,  0.75390225],
       [-0.41614684, -0.9899925 , -0.14550003],
       [ 0.28366219, -0.41614684,  1.        ]])

In [184]:
np.tan(array_01)

array([[-6.79971146, -0.45231566,  0.87144798],
       [-2.18503986, -0.14254654, -6.79971146],
       [-3.38051501, -2.18503986,  0.        ]])

In [185]:
np.sinh(array_01)

array([[1.49047883e+03, 4.05154190e+03, 5.48316123e+02],
       [3.62686041e+00, 1.00178749e+01, 1.49047883e+03],
       [7.42032106e+01, 3.62686041e+00, 0.00000000e+00]])

In [186]:
np.cosh(array_01)

array([[1.49047916e+03, 4.05154203e+03, 5.48317035e+02],
       [3.76219569e+00, 1.00676620e+01, 1.49047916e+03],
       [7.42099485e+01, 3.76219569e+00, 1.00000000e+00]])

In [187]:
np.tanh(array_01)

array([[0.99999977, 0.99999997, 0.99999834],
       [0.96402758, 0.99505475, 0.99999977],
       [0.9999092 , 0.96402758, 0.        ]])

In [188]:
array_01.flatten()

array([8, 9, 7, 2, 3, 8, 5, 2, 0])

In [189]:
array_02 = np.array([1,2,3])

In [190]:
np.expand_dims(array_02, axis = 0)

array([[1, 2, 3]])

In [191]:
np.expand_dims(array_02, axis = 1)

array([[1],
       [2],
       [3]])

In [192]:
array_03 = np.array([[1],[2],[3]])

In [193]:
print(array_03)

[[1]
 [2]
 [3]]


In [195]:
array_03 = array_03.squeeze()

In [196]:
print(array_03)

[1 2 3]
